// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dpa_rpc_nico.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetVNI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *DpaMetadata           `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	PfInfo        *PFVNI                 `protobuf:"bytes,2,opt,name=pf_info,json=pfInfo,proto3" json:"pf_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVNI) Reset() {
	*x = SetVNI{}
	mi := &file_dpa_rpc_nico_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVNI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVNI) ProtoMessage() {}

func (x *SetVNI) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_rpc_nico_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVNI.ProtoReflect.Descriptor instead.
func (*SetVNI) Descriptor() ([]byte, []int) {
	return file_dpa_rpc_nico_proto_rawDescGZIP(), []int{0}
}

func (x *SetVNI) GetMetadata() *DpaMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SetVNI) GetPfInfo() *PFVNI {
	if x != nil {
		return x.PfInfo
	}
	return nil
}

type DpaMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DpaId         string                 `protobuf:"bytes,1,opt,name=dpa_id,json=dpaId,proto3" json:"dpa_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Revision      string                 `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Transaction   string                 `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DpaMetadata) Reset() {
	*x = DpaMetadata{}
	mi := &file_dpa_rpc_nico_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DpaMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DpaMetadata) ProtoMessage() {}

func (x *DpaMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_rpc_nico_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DpaMetadata.ProtoReflect.Descriptor instead.
func (*DpaMetadata) Descriptor() ([]byte, []int) {
	return file_dpa_rpc_nico_proto_rawDescGZIP(), []int{1}
}

func (x *DpaMetadata) GetDpaId() string {
	if x != nil {
		return x.DpaId
	}
	return ""
}

func (x *DpaMetadata) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *DpaMetadata) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *DpaMetadata) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

type PFVNI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PfId          int32                  `protobuf:"varint,1,opt,name=pf_id,json=pfId,proto3" json:"pf_id,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Vni           int32                  `protobuf:"varint,3,opt,name=vni,proto3" json:"vni,omitempty"`
	SubnetIp      string                 `protobuf:"bytes,4,opt,name=subnet_ip,json=subnetIp,proto3" json:"subnet_ip,omitempty"`
	SubnetMask    int32                  `protobuf:"varint,5,opt,name=subnet_mask,json=subnetMask,proto3" json:"subnet_mask,omitempty"`
	DhcpIp        string                 `protobuf:"bytes,6,opt,name=dhcp_ip,json=dhcpIp,proto3" json:"dhcp_ip,omitempty"`
	HostIp        string                 `protobuf:"bytes,7,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PFVNI) Reset() {
	*x = PFVNI{}
	mi := &file_dpa_rpc_nico_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PFVNI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PFVNI) ProtoMessage() {}

func (x *PFVNI) ProtoReflect() protoreflect.Message {
	mi := &file_dpa_rpc_nico_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PFVNI.ProtoReflect.Descriptor instead.
func (*PFVNI) Descriptor() ([]byte, []int) {
	return file_dpa_rpc_nico_proto_rawDescGZIP(), []int{2}
}

func (x *PFVNI) GetPfId() int32 {
	if x != nil {
		return x.PfId
	}
	return 0
}

func (x *PFVNI) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *PFVNI) GetVni() int32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

func (x *PFVNI) GetSubnetIp() string {
	if x != nil {
		return x.SubnetIp
	}
	return ""
}

func (x *PFVNI) GetSubnetMask() int32 {
	if x != nil {
		return x.SubnetMask
	}
	return 0
}

func (x *PFVNI) GetDhcpIp() string {
	if x != nil {
		return x.DhcpIp
	}
	return ""
}

func (x *PFVNI) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

var File_dpa_rpc_nico_proto protoreflect.FileDescriptor

const file_dpa_rpc_nico_proto_rawDesc = "" +
	"\n" +
	"\x12dpa_rpc_nico.proto\x12\adpa_rpc\"c\n" +
	"\x06SetVNI\x120\n" +
	"\bmetadata\x18\x01 \x01(\v2\x14.dpa_rpc.DpaMetadataR\bmetadata\x12'\n" +
	"\apf_info\x18\x02 \x01(\v2\x0e.dpa_rpc.PFVNIR\x06pfInfo\"{\n" +
	"\vDpaMetadata\x12\x15\n" +
	"\x06dpa_id\x18\x01 \x01(\tR\x05dpaId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\tR\brevision\x12 \n" +
	"\vtransaction\x18\x04 \x01(\tR\vtransaction\"\xb0\x01\n" +
	"\x05PFVNI\x12\x13\n" +
	"\x05pf_id\x18\x01 \x01(\x05R\x04pfId\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x10\n" +
	"\x03vni\x18\x03 \x01(\x05R\x03vni\x12\x1b\n" +
	"\tsubnet_ip\x18\x04 \x01(\tR\bsubnetIp\x12\x1f\n" +
	"\vsubnet_mask\x18\x05 \x01(\x05R\n" +
	"subnetMask\x12\x17\n" +
	"\adhcp_ip\x18\x06 \x01(\tR\x06dhcpIp\x12\x17\n" +
	"\ahost_ip\x18\a \x01(\tR\x06hostIpBCZAgithub.com/NVIDIA/infra-controller/rest-api/workflow-schema/protob\x06proto3"

var (
	file_dpa_rpc_nico_proto_rawDescOnce sync.Once
	file_dpa_rpc_nico_proto_rawDescData []byte
)

func file_dpa_rpc_nico_proto_rawDescGZIP() []byte {
	file_dpa_rpc_nico_proto_rawDescOnce.Do(func() {
		file_dpa_rpc_nico_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dpa_rpc_nico_proto_rawDesc), len(file_dpa_rpc_nico_proto_rawDesc)))
	})
	return file_dpa_rpc_nico_proto_rawDescData
}

var file_dpa_rpc_nico_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dpa_rpc_nico_proto_goTypes = []any{
	(*SetVNI)(nil),      // 0: dpa_rpc.SetVNI
	(*DpaMetadata)(nil), // 1: dpa_rpc.DpaMetadata
	(*PFVNI)(nil),       // 2: dpa_rpc.PFVNI
}
var file_dpa_rpc_nico_proto_depIdxs = []int32{
	1, // 0: dpa_rpc.SetVNI.metadata:type_name -> dpa_rpc.DpaMetadata
	2, // 1: dpa_rpc.SetVNI.pf_info:type_name -> dpa_rpc.PFVNI
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dpa_rpc_nico_proto_init() }
func file_dpa_rpc_nico_proto_init() {
	if File_dpa_rpc_nico_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dpa_rpc_nico_proto_rawDesc), len(file_dpa_rpc_nico_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dpa_rpc_nico_proto_goTypes,
		DependencyIndexes: file_dpa_rpc_nico_proto_depIdxs,
		MessageInfos:      file_dpa_rpc_nico_proto_msgTypes,
	}.Build()
	File_dpa_rpc_nico_proto = out.File
	file_dpa_rpc_nico_proto_goTypes = nil
	file_dpa_rpc_nico_proto_depIdxs = nil
}
