// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: internal/proto/v1/nvswitch-manager.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vendor enumerates supported hardware vendors.
type Vendor int32

const (
	Vendor_VENDOR_UNKNOWN Vendor = 0
	Vendor_VENDOR_NVIDIA  Vendor = 1
)

// Enum value maps for Vendor.
var (
	Vendor_name = map[int32]string{
		0: "VENDOR_UNKNOWN",
		1: "VENDOR_NVIDIA",
	}
	Vendor_value = map[string]int32{
		"VENDOR_UNKNOWN": 0,
		"VENDOR_NVIDIA":  1,
	}
)

func (x Vendor) Enum() *Vendor {
	p := new(Vendor)
	*p = x
	return p
}

func (x Vendor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vendor) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_v1_nvswitch_manager_proto_enumTypes[0].Descriptor()
}

func (Vendor) Type() protoreflect.EnumType {
	return &file_internal_proto_v1_nvswitch_manager_proto_enumTypes[0]
}

func (x Vendor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vendor.Descriptor instead.
func (Vendor) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{0}
}

type StatusCode int32

const (
	StatusCode_SUCCESS          StatusCode = 0
	StatusCode_INVALID_ARGUMENT StatusCode = 1
	StatusCode_INTERNAL_ERROR   StatusCode = 2
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "SUCCESS",
		1: "INVALID_ARGUMENT",
		2: "INTERNAL_ERROR",
	}
	StatusCode_value = map[string]int32{
		"SUCCESS":          0,
		"INVALID_ARGUMENT": 1,
		"INTERNAL_ERROR":   2,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_v1_nvswitch_manager_proto_enumTypes[1].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_internal_proto_v1_nvswitch_manager_proto_enumTypes[1]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{1}
}

// PowerAction enumerates the Redfish ComputerSystem.Reset actions supported by NV-Switch trays.
type PowerAction int32

const (
	PowerAction_POWER_ACTION_UNKNOWN           PowerAction = 0
	PowerAction_POWER_ACTION_FORCE_OFF         PowerAction = 1
	PowerAction_POWER_ACTION_POWER_CYCLE       PowerAction = 2
	PowerAction_POWER_ACTION_GRACEFUL_SHUTDOWN PowerAction = 3
	PowerAction_POWER_ACTION_ON                PowerAction = 4
	PowerAction_POWER_ACTION_FORCE_ON          PowerAction = 5
	PowerAction_POWER_ACTION_GRACEFUL_RESTART  PowerAction = 6
	PowerAction_POWER_ACTION_FORCE_RESTART     PowerAction = 7
)

// Enum value maps for PowerAction.
var (
	PowerAction_name = map[int32]string{
		0: "POWER_ACTION_UNKNOWN",
		1: "POWER_ACTION_FORCE_OFF",
		2: "POWER_ACTION_POWER_CYCLE",
		3: "POWER_ACTION_GRACEFUL_SHUTDOWN",
		4: "POWER_ACTION_ON",
		5: "POWER_ACTION_FORCE_ON",
		6: "POWER_ACTION_GRACEFUL_RESTART",
		7: "POWER_ACTION_FORCE_RESTART",
	}
	PowerAction_value = map[string]int32{
		"POWER_ACTION_UNKNOWN":           0,
		"POWER_ACTION_FORCE_OFF":         1,
		"POWER_ACTION_POWER_CYCLE":       2,
		"POWER_ACTION_GRACEFUL_SHUTDOWN": 3,
		"POWER_ACTION_ON":                4,
		"POWER_ACTION_FORCE_ON":          5,
		"POWER_ACTION_GRACEFUL_RESTART":  6,
		"POWER_ACTION_FORCE_RESTART":     7,
	}
)

func (x PowerAction) Enum() *PowerAction {
	p := new(PowerAction)
	*p = x
	return p
}

func (x PowerAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerAction) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_v1_nvswitch_manager_proto_enumTypes[2].Descriptor()
}

func (PowerAction) Type() protoreflect.EnumType {
	return &file_internal_proto_v1_nvswitch_manager_proto_enumTypes[2]
}

func (x PowerAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerAction.Descriptor instead.
func (PowerAction) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{2}
}

// NVSwitchComponent enumerates the updatable components of an NV-Switch tray.
// Update sequence: BMC -> CPLD -> BIOS -> NVOS
type NVSwitchComponent int32

const (
	NVSwitchComponent_NVSWITCH_COMPONENT_UNKNOWN NVSwitchComponent = 0
	NVSwitchComponent_NVSWITCH_COMPONENT_BMC     NVSwitchComponent = 1 // BMC firmware via Redfish
	NVSwitchComponent_NVSWITCH_COMPONENT_CPLD    NVSwitchComponent = 2 // CPLD via NVOS SSH
	NVSwitchComponent_NVSWITCH_COMPONENT_BIOS    NVSwitchComponent = 3 // BIOS firmware via Redfish
	NVSwitchComponent_NVSWITCH_COMPONENT_NVOS    NVSwitchComponent = 4 // NVOS system image via SSH
)

// Enum value maps for NVSwitchComponent.
var (
	NVSwitchComponent_name = map[int32]string{
		0: "NVSWITCH_COMPONENT_UNKNOWN",
		1: "NVSWITCH_COMPONENT_BMC",
		2: "NVSWITCH_COMPONENT_CPLD",
		3: "NVSWITCH_COMPONENT_BIOS",
		4: "NVSWITCH_COMPONENT_NVOS",
	}
	NVSwitchComponent_value = map[string]int32{
		"NVSWITCH_COMPONENT_UNKNOWN": 0,
		"NVSWITCH_COMPONENT_BMC":     1,
		"NVSWITCH_COMPONENT_CPLD":    2,
		"NVSWITCH_COMPONENT_BIOS":    3,
		"NVSWITCH_COMPONENT_NVOS":    4,
	}
)

func (x NVSwitchComponent) Enum() *NVSwitchComponent {
	p := new(NVSwitchComponent)
	*p = x
	return p
}

func (x NVSwitchComponent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NVSwitchComponent) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_v1_nvswitch_manager_proto_enumTypes[3].Descriptor()
}

func (NVSwitchComponent) Type() protoreflect.EnumType {
	return &file_internal_proto_v1_nvswitch_manager_proto_enumTypes[3]
}

func (x NVSwitchComponent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NVSwitchComponent.Descriptor instead.
func (NVSwitchComponent) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{3}
}

// UpdateStrategy specifies how firmware is updated.
type UpdateStrategy int32

const (
	UpdateStrategy_UPDATE_STRATEGY_UNKNOWN UpdateStrategy = 0
	UpdateStrategy_UPDATE_STRATEGY_SCRIPT  UpdateStrategy = 1 // External shell scripts
	UpdateStrategy_UPDATE_STRATEGY_SSH     UpdateStrategy = 2 // Direct SSH commands
	UpdateStrategy_UPDATE_STRATEGY_REDFISH UpdateStrategy = 3 // Redfish API
)

// Enum value maps for UpdateStrategy.
var (
	UpdateStrategy_name = map[int32]string{
		0: "UPDATE_STRATEGY_UNKNOWN",
		1: "UPDATE_STRATEGY_SCRIPT",
		2: "UPDATE_STRATEGY_SSH",
		3: "UPDATE_STRATEGY_REDFISH",
	}
	UpdateStrategy_value = map[string]int32{
		"UPDATE_STRATEGY_UNKNOWN": 0,
		"UPDATE_STRATEGY_SCRIPT":  1,
		"UPDATE_STRATEGY_SSH":     2,
		"UPDATE_STRATEGY_REDFISH": 3,
	}
)

func (x UpdateStrategy) Enum() *UpdateStrategy {
	p := new(UpdateStrategy)
	*p = x
	return p
}

func (x UpdateStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_v1_nvswitch_manager_proto_enumTypes[4].Descriptor()
}

func (UpdateStrategy) Type() protoreflect.EnumType {
	return &file_internal_proto_v1_nvswitch_manager_proto_enumTypes[4]
}

func (x UpdateStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateStrategy.Descriptor instead.
func (UpdateStrategy) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{4}
}

// UpdateState represents the granular state of a firmware update.
type UpdateState int32

const (
	UpdateState_UPDATE_STATE_UNKNOWN         UpdateState = 0
	UpdateState_UPDATE_STATE_QUEUED          UpdateState = 1
	UpdateState_UPDATE_STATE_POWER_CYCLE     UpdateState = 2 // NVOS: power cycle via BMC (bundle updates only)
	UpdateState_UPDATE_STATE_WAIT_REACHABLE  UpdateState = 3 // NVOS: wait for switch to be reachable
	UpdateState_UPDATE_STATE_COPY            UpdateState = 4 // SSH: copying file to switch
	UpdateState_UPDATE_STATE_UPLOAD          UpdateState = 5 // SSH: nv action fetch / Redfish: upload
	UpdateState_UPDATE_STATE_INSTALL         UpdateState = 6 // Installing firmware
	UpdateState_UPDATE_STATE_POLL_COMPLETION UpdateState = 7 // Redfish: polling task
	UpdateState_UPDATE_STATE_VERIFY          UpdateState = 8 // Verifying version
	UpdateState_UPDATE_STATE_CLEANUP         UpdateState = 9 // Cleaning up temp files
	UpdateState_UPDATE_STATE_COMPLETED       UpdateState = 10
	UpdateState_UPDATE_STATE_FAILED          UpdateState = 11
	UpdateState_UPDATE_STATE_CANCELLED       UpdateState = 12 // Cancelled due to predecessor failure
)

// Enum value maps for UpdateState.
var (
	UpdateState_name = map[int32]string{
		0:  "UPDATE_STATE_UNKNOWN",
		1:  "UPDATE_STATE_QUEUED",
		2:  "UPDATE_STATE_POWER_CYCLE",
		3:  "UPDATE_STATE_WAIT_REACHABLE",
		4:  "UPDATE_STATE_COPY",
		5:  "UPDATE_STATE_UPLOAD",
		6:  "UPDATE_STATE_INSTALL",
		7:  "UPDATE_STATE_POLL_COMPLETION",
		8:  "UPDATE_STATE_VERIFY",
		9:  "UPDATE_STATE_CLEANUP",
		10: "UPDATE_STATE_COMPLETED",
		11: "UPDATE_STATE_FAILED",
		12: "UPDATE_STATE_CANCELLED",
	}
	UpdateState_value = map[string]int32{
		"UPDATE_STATE_UNKNOWN":         0,
		"UPDATE_STATE_QUEUED":          1,
		"UPDATE_STATE_POWER_CYCLE":     2,
		"UPDATE_STATE_WAIT_REACHABLE":  3,
		"UPDATE_STATE_COPY":            4,
		"UPDATE_STATE_UPLOAD":          5,
		"UPDATE_STATE_INSTALL":         6,
		"UPDATE_STATE_POLL_COMPLETION": 7,
		"UPDATE_STATE_VERIFY":          8,
		"UPDATE_STATE_CLEANUP":         9,
		"UPDATE_STATE_COMPLETED":       10,
		"UPDATE_STATE_FAILED":          11,
		"UPDATE_STATE_CANCELLED":       12,
	}
)

func (x UpdateState) Enum() *UpdateState {
	p := new(UpdateState)
	*p = x
	return p
}

func (x UpdateState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_v1_nvswitch_manager_proto_enumTypes[5].Descriptor()
}

func (UpdateState) Type() protoreflect.EnumType {
	return &file_internal_proto_v1_nvswitch_manager_proto_enumTypes[5]
}

func (x UpdateState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateState.Descriptor instead.
func (UpdateState) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{5}
}

// Credentials wraps around a username and password.
type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Subsystem represents a network-accessible subsystem with MAC, IP, port, and credentials.
type Subsystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddress    string                 `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Credentials   *Credentials           `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"` // Optional custom port (0 = default: 443 for BMC, 22 for NVOS)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subsystem) Reset() {
	*x = Subsystem{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subsystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subsystem) ProtoMessage() {}

func (x *Subsystem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subsystem.ProtoReflect.Descriptor instead.
func (*Subsystem) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{1}
}

func (x *Subsystem) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Subsystem) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Subsystem) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *Subsystem) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// BMCInfo contains BMC identity and metadata enriched from Redfish.
type BMCInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MacAddress      string                 `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress       string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	SerialNumber    string                 `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Model           string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Manufacturer    string                 `protobuf:"bytes,5,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	PartNumber      string                 `protobuf:"bytes,6,opt,name=part_number,json=partNumber,proto3" json:"part_number,omitempty"`
	FirmwareVersion string                 `protobuf:"bytes,7,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	Port            int32                  `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"` // Custom port (0 = default 443)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BMCInfo) Reset() {
	*x = BMCInfo{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BMCInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMCInfo) ProtoMessage() {}

func (x *BMCInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMCInfo.ProtoReflect.Descriptor instead.
func (*BMCInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{2}
}

func (x *BMCInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *BMCInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *BMCInfo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *BMCInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *BMCInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *BMCInfo) GetPartNumber() string {
	if x != nil {
		return x.PartNumber
	}
	return ""
}

func (x *BMCInfo) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *BMCInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// NVOSInfo contains NVOS identity and version information.
type NVOSInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddress    string                 `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"` // Custom port (0 = default 22)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NVOSInfo) Reset() {
	*x = NVOSInfo{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NVOSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVOSInfo) ProtoMessage() {}

func (x *NVOSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVOSInfo.ProtoReflect.Descriptor instead.
func (*NVOSInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{3}
}

func (x *NVOSInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NVOSInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NVOSInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NVOSInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Chassis contains chassis identity from Redfish.
type Chassis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chassis) Reset() {
	*x = Chassis{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chassis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chassis) ProtoMessage() {}

func (x *Chassis) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chassis.ProtoReflect.Descriptor instead.
func (*Chassis) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{4}
}

func (x *Chassis) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Chassis) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Chassis) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

// NVSwitchTray represents a complete NV-Switch tray.
type NVSwitchTray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // Service-generated UUID
	Vendor        Vendor                 `protobuf:"varint,2,opt,name=vendor,proto3,enum=v1.Vendor" json:"vendor,omitempty"`
	Bmc           *BMCInfo               `protobuf:"bytes,3,opt,name=bmc,proto3" json:"bmc,omitempty"`   // BMC subsystem info
	Nvos          *NVOSInfo              `protobuf:"bytes,4,opt,name=nvos,proto3" json:"nvos,omitempty"` // NVOS subsystem info
	Chassis       *Chassis               `protobuf:"bytes,5,opt,name=chassis,proto3" json:"chassis,omitempty"`
	CpldVersion   string                 `protobuf:"bytes,6,opt,name=cpld_version,json=cpldVersion,proto3" json:"cpld_version,omitempty"`
	RackId        string                 `protobuf:"bytes,7,opt,name=rack_id,json=rackId,proto3" json:"rack_id,omitempty"` // Optional rack identifier for grouping switches
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NVSwitchTray) Reset() {
	*x = NVSwitchTray{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NVSwitchTray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVSwitchTray) ProtoMessage() {}

func (x *NVSwitchTray) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVSwitchTray.ProtoReflect.Descriptor instead.
func (*NVSwitchTray) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{5}
}

func (x *NVSwitchTray) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NVSwitchTray) GetVendor() Vendor {
	if x != nil {
		return x.Vendor
	}
	return Vendor_VENDOR_UNKNOWN
}

func (x *NVSwitchTray) GetBmc() *BMCInfo {
	if x != nil {
		return x.Bmc
	}
	return nil
}

func (x *NVSwitchTray) GetNvos() *NVOSInfo {
	if x != nil {
		return x.Nvos
	}
	return nil
}

func (x *NVSwitchTray) GetChassis() *Chassis {
	if x != nil {
		return x.Chassis
	}
	return nil
}

func (x *NVSwitchTray) GetCpldVersion() string {
	if x != nil {
		return x.CpldVersion
	}
	return ""
}

func (x *NVSwitchTray) GetRackId() string {
	if x != nil {
		return x.RackId
	}
	return ""
}

// RegisterNVSwitchRequest contains all fields needed to register a switch.
type RegisterNVSwitchRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Vendor Vendor                 `protobuf:"varint,1,opt,name=vendor,proto3,enum=v1.Vendor" json:"vendor,omitempty"`
	// BMC subsystem (4 fields)
	Bmc *Subsystem `protobuf:"bytes,2,opt,name=bmc,proto3" json:"bmc,omitempty"`
	// NVOS subsystem (4 fields)
	Nvos *Subsystem `protobuf:"bytes,3,opt,name=nvos,proto3" json:"nvos,omitempty"`
	// Optional rack identifier for grouping switches
	RackId        string `protobuf:"bytes,4,opt,name=rack_id,json=rackId,proto3" json:"rack_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNVSwitchRequest) Reset() {
	*x = RegisterNVSwitchRequest{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNVSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNVSwitchRequest) ProtoMessage() {}

func (x *RegisterNVSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNVSwitchRequest.ProtoReflect.Descriptor instead.
func (*RegisterNVSwitchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterNVSwitchRequest) GetVendor() Vendor {
	if x != nil {
		return x.Vendor
	}
	return Vendor_VENDOR_UNKNOWN
}

func (x *RegisterNVSwitchRequest) GetBmc() *Subsystem {
	if x != nil {
		return x.Bmc
	}
	return nil
}

func (x *RegisterNVSwitchRequest) GetNvos() *Subsystem {
	if x != nil {
		return x.Nvos
	}
	return nil
}

func (x *RegisterNVSwitchRequest) GetRackId() string {
	if x != nil {
		return x.RackId
	}
	return ""
}

type RegisterNVSwitchesRequest struct {
	state                protoimpl.MessageState     `protogen:"open.v1"`
	RegistrationRequests []*RegisterNVSwitchRequest `protobuf:"bytes,1,rep,name=registration_requests,json=registrationRequests,proto3" json:"registration_requests,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterNVSwitchesRequest) Reset() {
	*x = RegisterNVSwitchesRequest{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNVSwitchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNVSwitchesRequest) ProtoMessage() {}

func (x *RegisterNVSwitchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNVSwitchesRequest.ProtoReflect.Descriptor instead.
func (*RegisterNVSwitchesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterNVSwitchesRequest) GetRegistrationRequests() []*RegisterNVSwitchRequest {
	if x != nil {
		return x.RegistrationRequests
	}
	return nil
}

type RegisterNVSwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // Service-generated UUID for the registered switch
	IsNew         bool                   `protobuf:"varint,2,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Status        StatusCode             `protobuf:"varint,4,opt,name=status,proto3,enum=v1.StatusCode" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNVSwitchResponse) Reset() {
	*x = RegisterNVSwitchResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNVSwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNVSwitchResponse) ProtoMessage() {}

func (x *RegisterNVSwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNVSwitchResponse.ProtoReflect.Descriptor instead.
func (*RegisterNVSwitchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterNVSwitchResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RegisterNVSwitchResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *RegisterNVSwitchResponse) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *RegisterNVSwitchResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_SUCCESS
}

func (x *RegisterNVSwitchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegisterNVSwitchesResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Responses     []*RegisterNVSwitchResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNVSwitchesResponse) Reset() {
	*x = RegisterNVSwitchesResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNVSwitchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNVSwitchesResponse) ProtoMessage() {}

func (x *RegisterNVSwitchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNVSwitchesResponse.ProtoReflect.Descriptor instead.
func (*RegisterNVSwitchesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterNVSwitchesResponse) GetResponses() []*RegisterNVSwitchResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

// NVSwitchRequest identifies switches by their UUID.
type NVSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuids         []string               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"` // Switch UUIDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NVSwitchRequest) Reset() {
	*x = NVSwitchRequest{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NVSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVSwitchRequest) ProtoMessage() {}

func (x *NVSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVSwitchRequest.ProtoReflect.Descriptor instead.
func (*NVSwitchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{10}
}

func (x *NVSwitchRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type NVSwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status        StatusCode             `protobuf:"varint,2,opt,name=status,proto3,enum=v1.StatusCode" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	BmcIp         string                 `protobuf:"bytes,4,opt,name=bmc_ip,json=bmcIp,proto3" json:"bmc_ip,omitempty"` // Set for direct PowerTarget responses; empty for registered switches
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NVSwitchResponse) Reset() {
	*x = NVSwitchResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NVSwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NVSwitchResponse) ProtoMessage() {}

func (x *NVSwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NVSwitchResponse.ProtoReflect.Descriptor instead.
func (*NVSwitchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{11}
}

func (x *NVSwitchResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NVSwitchResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_SUCCESS
}

func (x *NVSwitchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NVSwitchResponse) GetBmcIp() string {
	if x != nil {
		return x.BmcIp
	}
	return ""
}

// PowerTarget allows power control against a device without prior registration.
// Only IP and credentials are required; the registry and credential manager are bypassed.
type PowerTarget struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BmcIp          string                 `protobuf:"bytes,1,opt,name=bmc_ip,json=bmcIp,proto3" json:"bmc_ip,omitempty"`
	BmcCredentials *Credentials           `protobuf:"bytes,2,opt,name=bmc_credentials,json=bmcCredentials,proto3" json:"bmc_credentials,omitempty"`
	BmcPort        int32                  `protobuf:"varint,3,opt,name=bmc_port,json=bmcPort,proto3" json:"bmc_port,omitempty"` // 0 = default (443)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PowerTarget) Reset() {
	*x = PowerTarget{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerTarget) ProtoMessage() {}

func (x *PowerTarget) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerTarget.ProtoReflect.Descriptor instead.
func (*PowerTarget) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{12}
}

func (x *PowerTarget) GetBmcIp() string {
	if x != nil {
		return x.BmcIp
	}
	return ""
}

func (x *PowerTarget) GetBmcCredentials() *Credentials {
	if x != nil {
		return x.BmcCredentials
	}
	return nil
}

func (x *PowerTarget) GetBmcPort() int32 {
	if x != nil {
		return x.BmcPort
	}
	return 0
}

// FirmwareTarget allows firmware updates against a device without prior registration.
// BMC and NVOS MAC addresses, IPs, and credentials are all required.
type FirmwareTarget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BmcIp           string                 `protobuf:"bytes,1,opt,name=bmc_ip,json=bmcIp,proto3" json:"bmc_ip,omitempty"`
	BmcCredentials  *Credentials           `protobuf:"bytes,2,opt,name=bmc_credentials,json=bmcCredentials,proto3" json:"bmc_credentials,omitempty"`
	BmcPort         int32                  `protobuf:"varint,3,opt,name=bmc_port,json=bmcPort,proto3" json:"bmc_port,omitempty"` // 0 = default (443)
	NvosIp          string                 `protobuf:"bytes,4,opt,name=nvos_ip,json=nvosIp,proto3" json:"nvos_ip,omitempty"`     // NVOS SSH IP (can be same as bmc_ip)
	NvosCredentials *Credentials           `protobuf:"bytes,5,opt,name=nvos_credentials,json=nvosCredentials,proto3" json:"nvos_credentials,omitempty"`
	NvosPort        int32                  `protobuf:"varint,6,opt,name=nvos_port,json=nvosPort,proto3" json:"nvos_port,omitempty"` // 0 = default (22)
	Vendor          Vendor                 `protobuf:"varint,7,opt,name=vendor,proto3,enum=v1.Vendor" json:"vendor,omitempty"`      // Default: VENDOR_NVIDIA
	BmcMac          string                 `protobuf:"bytes,8,opt,name=bmc_mac,json=bmcMac,proto3" json:"bmc_mac,omitempty"`        // BMC MAC address (used as registration key)
	NvosMac         string                 `protobuf:"bytes,9,opt,name=nvos_mac,json=nvosMac,proto3" json:"nvos_mac,omitempty"`     // NVOS MAC address
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FirmwareTarget) Reset() {
	*x = FirmwareTarget{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareTarget) ProtoMessage() {}

func (x *FirmwareTarget) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareTarget.ProtoReflect.Descriptor instead.
func (*FirmwareTarget) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{13}
}

func (x *FirmwareTarget) GetBmcIp() string {
	if x != nil {
		return x.BmcIp
	}
	return ""
}

func (x *FirmwareTarget) GetBmcCredentials() *Credentials {
	if x != nil {
		return x.BmcCredentials
	}
	return nil
}

func (x *FirmwareTarget) GetBmcPort() int32 {
	if x != nil {
		return x.BmcPort
	}
	return 0
}

func (x *FirmwareTarget) GetNvosIp() string {
	if x != nil {
		return x.NvosIp
	}
	return ""
}

func (x *FirmwareTarget) GetNvosCredentials() *Credentials {
	if x != nil {
		return x.NvosCredentials
	}
	return nil
}

func (x *FirmwareTarget) GetNvosPort() int32 {
	if x != nil {
		return x.NvosPort
	}
	return 0
}

func (x *FirmwareTarget) GetVendor() Vendor {
	if x != nil {
		return x.Vendor
	}
	return Vendor_VENDOR_UNKNOWN
}

func (x *FirmwareTarget) GetBmcMac() string {
	if x != nil {
		return x.BmcMac
	}
	return ""
}

func (x *FirmwareTarget) GetNvosMac() string {
	if x != nil {
		return x.NvosMac
	}
	return ""
}

// PowerControlRequest specifies the switches and the power action to perform.
// Registered switches are identified by UUID; unregistered devices use PowerTarget.
type PowerControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuids         []string               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	Action        PowerAction            `protobuf:"varint,2,opt,name=action,proto3,enum=v1.PowerAction" json:"action,omitempty"`
	Targets       []*PowerTarget         `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerControlRequest) Reset() {
	*x = PowerControlRequest{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerControlRequest) ProtoMessage() {}

func (x *PowerControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerControlRequest.ProtoReflect.Descriptor instead.
func (*PowerControlRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{14}
}

func (x *PowerControlRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *PowerControlRequest) GetAction() PowerAction {
	if x != nil {
		return x.Action
	}
	return PowerAction_POWER_ACTION_UNKNOWN
}

func (x *PowerControlRequest) GetTargets() []*PowerTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type PowerControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*NVSwitchResponse    `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerControlResponse) Reset() {
	*x = PowerControlResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerControlResponse) ProtoMessage() {}

func (x *PowerControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerControlResponse.ProtoReflect.Descriptor instead.
func (*PowerControlResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{15}
}

func (x *PowerControlResponse) GetResponses() []*NVSwitchResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type GetNVSwitchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nvswitches    []*NVSwitchTray        `protobuf:"bytes,1,rep,name=nvswitches,proto3" json:"nvswitches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNVSwitchesResponse) Reset() {
	*x = GetNVSwitchesResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNVSwitchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNVSwitchesResponse) ProtoMessage() {}

func (x *GetNVSwitchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNVSwitchesResponse.ProtoReflect.Descriptor instead.
func (*GetNVSwitchesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{16}
}

func (x *GetNVSwitchesResponse) GetNvswitches() []*NVSwitchTray {
	if x != nil {
		return x.Nvswitches
	}
	return nil
}

// FirmwareBundle represents a firmware package with multiple components.
type FirmwareBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // Unique bundle version identifier
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Components    []*ComponentInfo       `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareBundle) Reset() {
	*x = FirmwareBundle{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareBundle) ProtoMessage() {}

func (x *FirmwareBundle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareBundle.ProtoReflect.Descriptor instead.
func (*FirmwareBundle) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{17}
}

func (x *FirmwareBundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FirmwareBundle) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FirmwareBundle) GetComponents() []*ComponentInfo {
	if x != nil {
		return x.Components
	}
	return nil
}

// ComponentInfo describes a component within a bundle.
type ComponentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // Component name (firmware, cpld, nvos)
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`   // Component version
	Strategy      string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"` // Update strategy (redfish, ssh, script)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentInfo) Reset() {
	*x = ComponentInfo{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentInfo) ProtoMessage() {}

func (x *ComponentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentInfo.ProtoReflect.Descriptor instead.
func (*ComponentInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{18}
}

func (x *ComponentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ComponentInfo) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

// ListBundlesResponse returns available firmware bundles.
type ListBundlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundles       []*FirmwareBundle      `protobuf:"bytes,1,rep,name=bundles,proto3" json:"bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBundlesResponse) Reset() {
	*x = ListBundlesResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBundlesResponse) ProtoMessage() {}

func (x *ListBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBundlesResponse.ProtoReflect.Descriptor instead.
func (*ListBundlesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{19}
}

func (x *ListBundlesResponse) GetBundles() []*FirmwareBundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

// QueueUpdateRequest queues firmware updates for one or more components.
// If components is empty, all components in the bundle are updated in sequence.
type QueueUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwitchUuid    string                 `protobuf:"bytes,1,opt,name=switch_uuid,json=switchUuid,proto3" json:"switch_uuid,omitempty"`                 // UUID of the NV-Switch to update
	BundleVersion string                 `protobuf:"bytes,2,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`        // Version of the firmware bundle
	Components    []NVSwitchComponent    `protobuf:"varint,3,rep,packed,name=components,proto3,enum=v1.NVSwitchComponent" json:"components,omitempty"` // Components to update (empty = all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueUpdateRequest) Reset() {
	*x = QueueUpdateRequest{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdateRequest) ProtoMessage() {}

func (x *QueueUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdateRequest.ProtoReflect.Descriptor instead.
func (*QueueUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{20}
}

func (x *QueueUpdateRequest) GetSwitchUuid() string {
	if x != nil {
		return x.SwitchUuid
	}
	return ""
}

func (x *QueueUpdateRequest) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *QueueUpdateRequest) GetComponents() []NVSwitchComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

// QueueUpdateResponse returns the queued updates.
type QueueUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*FirmwareUpdateInfo  `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueUpdateResponse) Reset() {
	*x = QueueUpdateResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdateResponse) ProtoMessage() {}

func (x *QueueUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdateResponse.ProtoReflect.Descriptor instead.
func (*QueueUpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{21}
}

func (x *QueueUpdateResponse) GetUpdates() []*FirmwareUpdateInfo {
	if x != nil {
		return x.Updates
	}
	return nil
}

// QueueUpdatesRequest queues firmware updates for multiple switches.
// Registered switches are identified by UUID; unregistered devices use FirmwareTarget.
//
// `switch_uuids` and `targets` are mutually exclusive: a single request must
// populate exactly one of them. The handler does not deduplicate across the
// two lists, so allowing both would risk queuing duplicate updates for any
// device whose UUID and FirmwareTarget are both supplied. Callers with mixed
// inventory should issue one RPC per registration state. A request that
// populates neither is rejected for the same reason it would be a no-op.
//
// Whichever list is populated is processed best-effort, per item: a failure
// for one switch (invalid UUID, validation, auto-registration, queue
// rejection) does not abort processing of the remaining items and does not
// produce a non-OK gRPC status. Callers must inspect each
// `QueueUpdatesResponse.results[i].status` to determine per-item outcome.
// The RPC only returns a top-level error on global failures (firmware
// manager uninitialized, malformed `components` enum value, or violation of
// the mutual-exclusivity contract above).
type QueueUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwitchUuids   []string               `protobuf:"bytes,1,rep,name=switch_uuids,json=switchUuids,proto3" json:"switch_uuids,omitempty"`              // UUIDs of registered NV-Switches to update; mutually exclusive with `targets`. Processed best-effort.
	BundleVersion string                 `protobuf:"bytes,2,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`        // Version of the firmware bundle
	Components    []NVSwitchComponent    `protobuf:"varint,3,rep,packed,name=components,proto3,enum=v1.NVSwitchComponent" json:"components,omitempty"` // Components to update (empty = all)
	Targets       []*FirmwareTarget      `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`                                         // Unregistered switches (auto-registered before update); mutually exclusive with `switch_uuids`. Processed best-effort.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueUpdatesRequest) Reset() {
	*x = QueueUpdatesRequest{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdatesRequest) ProtoMessage() {}

func (x *QueueUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdatesRequest.ProtoReflect.Descriptor instead.
func (*QueueUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{22}
}

func (x *QueueUpdatesRequest) GetSwitchUuids() []string {
	if x != nil {
		return x.SwitchUuids
	}
	return nil
}

func (x *QueueUpdatesRequest) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *QueueUpdatesRequest) GetComponents() []NVSwitchComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *QueueUpdatesRequest) GetTargets() []*FirmwareTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

// QueueUpdatesResponse returns the results for each switch. Length and
// ordering correspond to whichever of `switch_uuids` or `targets` was
// populated in the originating request (the two are mutually exclusive).
// Each entry reports its own outcome; see QueueUpdatesRequest for the
// best-effort contract.
type QueueUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*QueueUpdateResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueUpdatesResponse) Reset() {
	*x = QueueUpdatesResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdatesResponse) ProtoMessage() {}

func (x *QueueUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdatesResponse.ProtoReflect.Descriptor instead.
func (*QueueUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{23}
}

func (x *QueueUpdatesResponse) GetResults() []*QueueUpdateResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// QueueUpdateResult contains the result for a single switch update.
type QueueUpdateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwitchUuid    string                 `protobuf:"bytes,1,opt,name=switch_uuid,json=switchUuid,proto3" json:"switch_uuid,omitempty"` // UUID of the switch
	Status        StatusCode             `protobuf:"varint,2,opt,name=status,proto3,enum=v1.StatusCode" json:"status,omitempty"`       // SUCCESS or error; per-item outcome under QueueUpdatesRequest's best-effort contract
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                             // Error message if status != SUCCESS
	Updates       []*FirmwareUpdateInfo  `protobuf:"bytes,4,rep,name=updates,proto3" json:"updates,omitempty"`                         // Queued updates if successful
	BmcIp         string                 `protobuf:"bytes,5,opt,name=bmc_ip,json=bmcIp,proto3" json:"bmc_ip,omitempty"`                // Set for FirmwareTarget responses; empty for UUID-based
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueUpdateResult) Reset() {
	*x = QueueUpdateResult{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueUpdateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueUpdateResult) ProtoMessage() {}

func (x *QueueUpdateResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueUpdateResult.ProtoReflect.Descriptor instead.
func (*QueueUpdateResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{24}
}

func (x *QueueUpdateResult) GetSwitchUuid() string {
	if x != nil {
		return x.SwitchUuid
	}
	return ""
}

func (x *QueueUpdateResult) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_SUCCESS
}

func (x *QueueUpdateResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueueUpdateResult) GetUpdates() []*FirmwareUpdateInfo {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *QueueUpdateResult) GetBmcIp() string {
	if x != nil {
		return x.BmcIp
	}
	return ""
}

// GetUpdateRequest gets a specific update by ID.
type GetUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateId      string                 `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdateRequest) Reset() {
	*x = GetUpdateRequest{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdateRequest) ProtoMessage() {}

func (x *GetUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdateRequest.ProtoReflect.Descriptor instead.
func (*GetUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{25}
}

func (x *GetUpdateRequest) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

// GetUpdateResponse returns a single update.
type GetUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *FirmwareUpdateInfo    `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdateResponse) Reset() {
	*x = GetUpdateResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdateResponse) ProtoMessage() {}

func (x *GetUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdateResponse.ProtoReflect.Descriptor instead.
func (*GetUpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{26}
}

func (x *GetUpdateResponse) GetUpdate() *FirmwareUpdateInfo {
	if x != nil {
		return x.Update
	}
	return nil
}

// GetUpdatesForSwitchRequest gets all updates for a switch.
type GetUpdatesForSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwitchUuid    string                 `protobuf:"bytes,1,opt,name=switch_uuid,json=switchUuid,proto3" json:"switch_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdatesForSwitchRequest) Reset() {
	*x = GetUpdatesForSwitchRequest{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesForSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesForSwitchRequest) ProtoMessage() {}

func (x *GetUpdatesForSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesForSwitchRequest.ProtoReflect.Descriptor instead.
func (*GetUpdatesForSwitchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{27}
}

func (x *GetUpdatesForSwitchRequest) GetSwitchUuid() string {
	if x != nil {
		return x.SwitchUuid
	}
	return ""
}

// GetUpdatesForSwitchResponse returns updates for a switch.
type GetUpdatesForSwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*FirmwareUpdateInfo  `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdatesForSwitchResponse) Reset() {
	*x = GetUpdatesForSwitchResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdatesForSwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdatesForSwitchResponse) ProtoMessage() {}

func (x *GetUpdatesForSwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdatesForSwitchResponse.ProtoReflect.Descriptor instead.
func (*GetUpdatesForSwitchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{28}
}

func (x *GetUpdatesForSwitchResponse) GetUpdates() []*FirmwareUpdateInfo {
	if x != nil {
		return x.Updates
	}
	return nil
}

// GetAllUpdatesResponse returns all firmware updates.
type GetAllUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*FirmwareUpdateInfo  `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUpdatesResponse) Reset() {
	*x = GetAllUpdatesResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUpdatesResponse) ProtoMessage() {}

func (x *GetAllUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUpdatesResponse.ProtoReflect.Descriptor instead.
func (*GetAllUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{29}
}

func (x *GetAllUpdatesResponse) GetUpdates() []*FirmwareUpdateInfo {
	if x != nil {
		return x.Updates
	}
	return nil
}

// CancelUpdateRequest cancels an update.
type CancelUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateId      string                 `protobuf:"bytes,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUpdateRequest) Reset() {
	*x = CancelUpdateRequest{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUpdateRequest) ProtoMessage() {}

func (x *CancelUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUpdateRequest.ProtoReflect.Descriptor instead.
func (*CancelUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{30}
}

func (x *CancelUpdateRequest) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

// CancelUpdateResponse confirms cancellation.
type CancelUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUpdateResponse) Reset() {
	*x = CancelUpdateResponse{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUpdateResponse) ProtoMessage() {}

func (x *CancelUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUpdateResponse.ProtoReflect.Descriptor instead.
func (*CancelUpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{31}
}

func (x *CancelUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FirmwareUpdateInfo contains full details of a firmware update operation.
type FirmwareUpdateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Unique update ID (UUID)
	SwitchUuid    string                 `protobuf:"bytes,2,opt,name=switch_uuid,json=switchUuid,proto3" json:"switch_uuid,omitempty"`
	Component     NVSwitchComponent      `protobuf:"varint,3,opt,name=component,proto3,enum=v1.NVSwitchComponent" json:"component,omitempty"`
	BundleVersion string                 `protobuf:"bytes,4,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	Strategy      UpdateStrategy         `protobuf:"varint,5,opt,name=strategy,proto3,enum=v1.UpdateStrategy" json:"strategy,omitempty"`
	State         UpdateState            `protobuf:"varint,6,opt,name=state,proto3,enum=v1.UpdateState" json:"state,omitempty"`
	VersionFrom   string                 `protobuf:"bytes,7,opt,name=version_from,json=versionFrom,proto3" json:"version_from,omitempty"`
	VersionTo     string                 `protobuf:"bytes,8,opt,name=version_to,json=versionTo,proto3" json:"version_to,omitempty"`
	VersionActual string                 `protobuf:"bytes,9,opt,name=version_actual,json=versionActual,proto3" json:"version_actual,omitempty"` // Actual version after update
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Sequencing fields for multi-component updates
	BundleUpdateId string `protobuf:"bytes,13,opt,name=bundle_update_id,json=bundleUpdateId,proto3" json:"bundle_update_id,omitempty"` // Groups related updates (UUID, optional)
	SequenceOrder  int32  `protobuf:"varint,14,opt,name=sequence_order,json=sequenceOrder,proto3" json:"sequence_order,omitempty"`     // Order within bundle update (1, 2, 3...)
	PredecessorId  string `protobuf:"bytes,15,opt,name=predecessor_id,json=predecessorId,proto3" json:"predecessor_id,omitempty"`      // Must complete before this one starts (UUID, optional)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FirmwareUpdateInfo) Reset() {
	*x = FirmwareUpdateInfo{}
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareUpdateInfo) ProtoMessage() {}

func (x *FirmwareUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_nvswitch_manager_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareUpdateInfo.ProtoReflect.Descriptor instead.
func (*FirmwareUpdateInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP(), []int{32}
}

func (x *FirmwareUpdateInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FirmwareUpdateInfo) GetSwitchUuid() string {
	if x != nil {
		return x.SwitchUuid
	}
	return ""
}

func (x *FirmwareUpdateInfo) GetComponent() NVSwitchComponent {
	if x != nil {
		return x.Component
	}
	return NVSwitchComponent_NVSWITCH_COMPONENT_UNKNOWN
}

func (x *FirmwareUpdateInfo) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *FirmwareUpdateInfo) GetStrategy() UpdateStrategy {
	if x != nil {
		return x.Strategy
	}
	return UpdateStrategy_UPDATE_STRATEGY_UNKNOWN
}

func (x *FirmwareUpdateInfo) GetState() UpdateState {
	if x != nil {
		return x.State
	}
	return UpdateState_UPDATE_STATE_UNKNOWN
}

func (x *FirmwareUpdateInfo) GetVersionFrom() string {
	if x != nil {
		return x.VersionFrom
	}
	return ""
}

func (x *FirmwareUpdateInfo) GetVersionTo() string {
	if x != nil {
		return x.VersionTo
	}
	return ""
}

func (x *FirmwareUpdateInfo) GetVersionActual() string {
	if x != nil {
		return x.VersionActual
	}
	return ""
}

func (x *FirmwareUpdateInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FirmwareUpdateInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FirmwareUpdateInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *FirmwareUpdateInfo) GetBundleUpdateId() string {
	if x != nil {
		return x.BundleUpdateId
	}
	return ""
}

func (x *FirmwareUpdateInfo) GetSequenceOrder() int32 {
	if x != nil {
		return x.SequenceOrder
	}
	return 0
}

func (x *FirmwareUpdateInfo) GetPredecessorId() string {
	if x != nil {
		return x.PredecessorId
	}
	return ""
}

var File_internal_proto_v1_nvswitch_manager_proto protoreflect.FileDescriptor

const file_internal_proto_v1_nvswitch_manager_proto_rawDesc = "" +
	"\n" +
	"(internal/proto/v1/nvswitch-manager.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\vCredentials\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x92\x01\n" +
	"\tSubsystem\x12\x1f\n" +
	"\vmac_address\x18\x01 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x121\n" +
	"\vcredentials\x18\x03 \x01(\v2\x0f.v1.CredentialsR\vcredentials\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\"\x88\x02\n" +
	"\aBMCInfo\x12\x1f\n" +
	"\vmac_address\x18\x01 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumber\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\"\n" +
	"\fmanufacturer\x18\x05 \x01(\tR\fmanufacturer\x12\x1f\n" +
	"\vpart_number\x18\x06 \x01(\tR\n" +
	"partNumber\x12)\n" +
	"\x10firmware_version\x18\a \x01(\tR\x0ffirmwareVersion\x12\x12\n" +
	"\x04port\x18\b \x01(\x05R\x04port\"x\n" +
	"\bNVOSInfo\x12\x1f\n" +
	"\vmac_address\x18\x01 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\"h\n" +
	"\aChassis\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\"\n" +
	"\fmanufacturer\x18\x03 \x01(\tR\fmanufacturer\"\xea\x01\n" +
	"\fNVSwitchTray\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\"\n" +
	"\x06vendor\x18\x02 \x01(\x0e2\n" +
	".v1.VendorR\x06vendor\x12\x1d\n" +
	"\x03bmc\x18\x03 \x01(\v2\v.v1.BMCInfoR\x03bmc\x12 \n" +
	"\x04nvos\x18\x04 \x01(\v2\f.v1.NVOSInfoR\x04nvos\x12%\n" +
	"\achassis\x18\x05 \x01(\v2\v.v1.ChassisR\achassis\x12!\n" +
	"\fcpld_version\x18\x06 \x01(\tR\vcpldVersion\x12\x17\n" +
	"\arack_id\x18\a \x01(\tR\x06rackId\"\x9a\x01\n" +
	"\x17RegisterNVSwitchRequest\x12\"\n" +
	"\x06vendor\x18\x01 \x01(\x0e2\n" +
	".v1.VendorR\x06vendor\x12\x1f\n" +
	"\x03bmc\x18\x02 \x01(\v2\r.v1.SubsystemR\x03bmc\x12!\n" +
	"\x04nvos\x18\x03 \x01(\v2\r.v1.SubsystemR\x04nvos\x12\x17\n" +
	"\arack_id\x18\x04 \x01(\tR\x06rackId\"m\n" +
	"\x19RegisterNVSwitchesRequest\x12P\n" +
	"\x15registration_requests\x18\x01 \x03(\v2\x1b.v1.RegisterNVSwitchRequestR\x14registrationRequests\"\xb9\x01\n" +
	"\x18RegisterNVSwitchResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x15\n" +
	"\x06is_new\x18\x02 \x01(\bR\x05isNew\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12&\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0e.v1.StatusCodeR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"X\n" +
	"\x1aRegisterNVSwitchesResponse\x12:\n" +
	"\tresponses\x18\x01 \x03(\v2\x1c.v1.RegisterNVSwitchResponseR\tresponses\"'\n" +
	"\x0fNVSwitchRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\"{\n" +
	"\x10NVSwitchResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.v1.StatusCodeR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x15\n" +
	"\x06bmc_ip\x18\x04 \x01(\tR\x05bmcIp\"y\n" +
	"\vPowerTarget\x12\x15\n" +
	"\x06bmc_ip\x18\x01 \x01(\tR\x05bmcIp\x128\n" +
	"\x0fbmc_credentials\x18\x02 \x01(\v2\x0f.v1.CredentialsR\x0ebmcCredentials\x12\x19\n" +
	"\bbmc_port\x18\x03 \x01(\x05R\abmcPort\"\xc6\x02\n" +
	"\x0eFirmwareTarget\x12\x15\n" +
	"\x06bmc_ip\x18\x01 \x01(\tR\x05bmcIp\x128\n" +
	"\x0fbmc_credentials\x18\x02 \x01(\v2\x0f.v1.CredentialsR\x0ebmcCredentials\x12\x19\n" +
	"\bbmc_port\x18\x03 \x01(\x05R\abmcPort\x12\x17\n" +
	"\anvos_ip\x18\x04 \x01(\tR\x06nvosIp\x12:\n" +
	"\x10nvos_credentials\x18\x05 \x01(\v2\x0f.v1.CredentialsR\x0fnvosCredentials\x12\x1b\n" +
	"\tnvos_port\x18\x06 \x01(\x05R\bnvosPort\x12\"\n" +
	"\x06vendor\x18\a \x01(\x0e2\n" +
	".v1.VendorR\x06vendor\x12\x17\n" +
	"\abmc_mac\x18\b \x01(\tR\x06bmcMac\x12\x19\n" +
	"\bnvos_mac\x18\t \x01(\tR\anvosMac\"\x7f\n" +
	"\x13PowerControlRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\x12'\n" +
	"\x06action\x18\x02 \x01(\x0e2\x0f.v1.PowerActionR\x06action\x12)\n" +
	"\atargets\x18\x03 \x03(\v2\x0f.v1.PowerTargetR\atargets\"J\n" +
	"\x14PowerControlResponse\x122\n" +
	"\tresponses\x18\x01 \x03(\v2\x14.v1.NVSwitchResponseR\tresponses\"I\n" +
	"\x15GetNVSwitchesResponse\x120\n" +
	"\n" +
	"nvswitches\x18\x01 \x03(\v2\x10.v1.NVSwitchTrayR\n" +
	"nvswitches\"\x7f\n" +
	"\x0eFirmwareBundle\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x121\n" +
	"\n" +
	"components\x18\x03 \x03(\v2\x11.v1.ComponentInfoR\n" +
	"components\"Y\n" +
	"\rComponentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\"C\n" +
	"\x13ListBundlesResponse\x12,\n" +
	"\abundles\x18\x01 \x03(\v2\x12.v1.FirmwareBundleR\abundles\"\x93\x01\n" +
	"\x12QueueUpdateRequest\x12\x1f\n" +
	"\vswitch_uuid\x18\x01 \x01(\tR\n" +
	"switchUuid\x12%\n" +
	"\x0ebundle_version\x18\x02 \x01(\tR\rbundleVersion\x125\n" +
	"\n" +
	"components\x18\x03 \x03(\x0e2\x15.v1.NVSwitchComponentR\n" +
	"components\"G\n" +
	"\x13QueueUpdateResponse\x120\n" +
	"\aupdates\x18\x01 \x03(\v2\x16.v1.FirmwareUpdateInfoR\aupdates\"\xc4\x01\n" +
	"\x13QueueUpdatesRequest\x12!\n" +
	"\fswitch_uuids\x18\x01 \x03(\tR\vswitchUuids\x12%\n" +
	"\x0ebundle_version\x18\x02 \x01(\tR\rbundleVersion\x125\n" +
	"\n" +
	"components\x18\x03 \x03(\x0e2\x15.v1.NVSwitchComponentR\n" +
	"components\x12,\n" +
	"\atargets\x18\x04 \x03(\v2\x12.v1.FirmwareTargetR\atargets\"G\n" +
	"\x14QueueUpdatesResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.v1.QueueUpdateResultR\aresults\"\xbb\x01\n" +
	"\x11QueueUpdateResult\x12\x1f\n" +
	"\vswitch_uuid\x18\x01 \x01(\tR\n" +
	"switchUuid\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.v1.StatusCodeR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x120\n" +
	"\aupdates\x18\x04 \x03(\v2\x16.v1.FirmwareUpdateInfoR\aupdates\x12\x15\n" +
	"\x06bmc_ip\x18\x05 \x01(\tR\x05bmcIp\"/\n" +
	"\x10GetUpdateRequest\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\"C\n" +
	"\x11GetUpdateResponse\x12.\n" +
	"\x06update\x18\x01 \x01(\v2\x16.v1.FirmwareUpdateInfoR\x06update\"=\n" +
	"\x1aGetUpdatesForSwitchRequest\x12\x1f\n" +
	"\vswitch_uuid\x18\x01 \x01(\tR\n" +
	"switchUuid\"O\n" +
	"\x1bGetUpdatesForSwitchResponse\x120\n" +
	"\aupdates\x18\x01 \x03(\v2\x16.v1.FirmwareUpdateInfoR\aupdates\"I\n" +
	"\x15GetAllUpdatesResponse\x120\n" +
	"\aupdates\x18\x01 \x03(\v2\x16.v1.FirmwareUpdateInfoR\aupdates\"2\n" +
	"\x13CancelUpdateRequest\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\tR\bupdateId\"J\n" +
	"\x14CancelUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf4\x04\n" +
	"\x12FirmwareUpdateInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vswitch_uuid\x18\x02 \x01(\tR\n" +
	"switchUuid\x123\n" +
	"\tcomponent\x18\x03 \x01(\x0e2\x15.v1.NVSwitchComponentR\tcomponent\x12%\n" +
	"\x0ebundle_version\x18\x04 \x01(\tR\rbundleVersion\x12.\n" +
	"\bstrategy\x18\x05 \x01(\x0e2\x12.v1.UpdateStrategyR\bstrategy\x12%\n" +
	"\x05state\x18\x06 \x01(\x0e2\x0f.v1.UpdateStateR\x05state\x12!\n" +
	"\fversion_from\x18\a \x01(\tR\vversionFrom\x12\x1d\n" +
	"\n" +
	"version_to\x18\b \x01(\tR\tversionTo\x12%\n" +
	"\x0eversion_actual\x18\t \x01(\tR\rversionActual\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12(\n" +
	"\x10bundle_update_id\x18\r \x01(\tR\x0ebundleUpdateId\x12%\n" +
	"\x0esequence_order\x18\x0e \x01(\x05R\rsequenceOrder\x12%\n" +
	"\x0epredecessor_id\x18\x0f \x01(\tR\rpredecessorId*/\n" +
	"\x06Vendor\x12\x12\n" +
	"\x0eVENDOR_UNKNOWN\x10\x00\x12\x11\n" +
	"\rVENDOR_NVIDIA\x10\x01*C\n" +
	"\n" +
	"StatusCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x01\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x02*\xf8\x01\n" +
	"\vPowerAction\x12\x18\n" +
	"\x14POWER_ACTION_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16POWER_ACTION_FORCE_OFF\x10\x01\x12\x1c\n" +
	"\x18POWER_ACTION_POWER_CYCLE\x10\x02\x12\"\n" +
	"\x1ePOWER_ACTION_GRACEFUL_SHUTDOWN\x10\x03\x12\x13\n" +
	"\x0fPOWER_ACTION_ON\x10\x04\x12\x19\n" +
	"\x15POWER_ACTION_FORCE_ON\x10\x05\x12!\n" +
	"\x1dPOWER_ACTION_GRACEFUL_RESTART\x10\x06\x12\x1e\n" +
	"\x1aPOWER_ACTION_FORCE_RESTART\x10\a*\xa6\x01\n" +
	"\x11NVSwitchComponent\x12\x1e\n" +
	"\x1aNVSWITCH_COMPONENT_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16NVSWITCH_COMPONENT_BMC\x10\x01\x12\x1b\n" +
	"\x17NVSWITCH_COMPONENT_CPLD\x10\x02\x12\x1b\n" +
	"\x17NVSWITCH_COMPONENT_BIOS\x10\x03\x12\x1b\n" +
	"\x17NVSWITCH_COMPONENT_NVOS\x10\x04*\x7f\n" +
	"\x0eUpdateStrategy\x12\x1b\n" +
	"\x17UPDATE_STRATEGY_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16UPDATE_STRATEGY_SCRIPT\x10\x01\x12\x17\n" +
	"\x13UPDATE_STRATEGY_SSH\x10\x02\x12\x1b\n" +
	"\x17UPDATE_STRATEGY_REDFISH\x10\x03*\xef\x02\n" +
	"\vUpdateState\x12\x18\n" +
	"\x14UPDATE_STATE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13UPDATE_STATE_QUEUED\x10\x01\x12\x1c\n" +
	"\x18UPDATE_STATE_POWER_CYCLE\x10\x02\x12\x1f\n" +
	"\x1bUPDATE_STATE_WAIT_REACHABLE\x10\x03\x12\x15\n" +
	"\x11UPDATE_STATE_COPY\x10\x04\x12\x17\n" +
	"\x13UPDATE_STATE_UPLOAD\x10\x05\x12\x18\n" +
	"\x14UPDATE_STATE_INSTALL\x10\x06\x12 \n" +
	"\x1cUPDATE_STATE_POLL_COMPLETION\x10\a\x12\x17\n" +
	"\x13UPDATE_STATE_VERIFY\x10\b\x12\x18\n" +
	"\x14UPDATE_STATE_CLEANUP\x10\t\x12\x1a\n" +
	"\x16UPDATE_STATE_COMPLETED\x10\n" +
	"\x12\x17\n" +
	"\x13UPDATE_STATE_FAILED\x10\v\x12\x1a\n" +
	"\x16UPDATE_STATE_CANCELLED\x10\f2\xc6\x05\n" +
	"\x0fNVSwitchManager\x12S\n" +
	"\x12RegisterNVSwitches\x12\x1d.v1.RegisterNVSwitchesRequest\x1a\x1e.v1.RegisterNVSwitchesResponse\x12?\n" +
	"\rGetNVSwitches\x12\x13.v1.NVSwitchRequest\x1a\x19.v1.GetNVSwitchesResponse\x12>\n" +
	"\vListBundles\x12\x16.google.protobuf.Empty\x1a\x17.v1.ListBundlesResponse\x12>\n" +
	"\vQueueUpdate\x12\x16.v1.QueueUpdateRequest\x1a\x17.v1.QueueUpdateResponse\x12A\n" +
	"\fQueueUpdates\x12\x17.v1.QueueUpdatesRequest\x1a\x18.v1.QueueUpdatesResponse\x128\n" +
	"\tGetUpdate\x12\x14.v1.GetUpdateRequest\x1a\x15.v1.GetUpdateResponse\x12V\n" +
	"\x13GetUpdatesForSwitch\x12\x1e.v1.GetUpdatesForSwitchRequest\x1a\x1f.v1.GetUpdatesForSwitchResponse\x12B\n" +
	"\rGetAllUpdates\x12\x16.google.protobuf.Empty\x1a\x19.v1.GetAllUpdatesResponse\x12A\n" +
	"\fCancelUpdate\x12\x17.v1.CancelUpdateRequest\x1a\x18.v1.CancelUpdateResponse\x12A\n" +
	"\fPowerControl\x12\x17.v1.PowerControlRequest\x1a\x18.v1.PowerControlResponseB\n" +
	"Z\bproto/v1b\x06proto3"

var (
	file_internal_proto_v1_nvswitch_manager_proto_rawDescOnce sync.Once
	file_internal_proto_v1_nvswitch_manager_proto_rawDescData []byte
)

func file_internal_proto_v1_nvswitch_manager_proto_rawDescGZIP() []byte {
	file_internal_proto_v1_nvswitch_manager_proto_rawDescOnce.Do(func() {
		file_internal_proto_v1_nvswitch_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_v1_nvswitch_manager_proto_rawDesc), len(file_internal_proto_v1_nvswitch_manager_proto_rawDesc)))
	})
	return file_internal_proto_v1_nvswitch_manager_proto_rawDescData
}

var file_internal_proto_v1_nvswitch_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_internal_proto_v1_nvswitch_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_internal_proto_v1_nvswitch_manager_proto_goTypes = []any{
	(Vendor)(0),                         // 0: v1.Vendor
	(StatusCode)(0),                     // 1: v1.StatusCode
	(PowerAction)(0),                    // 2: v1.PowerAction
	(NVSwitchComponent)(0),              // 3: v1.NVSwitchComponent
	(UpdateStrategy)(0),                 // 4: v1.UpdateStrategy
	(UpdateState)(0),                    // 5: v1.UpdateState
	(*Credentials)(nil),                 // 6: v1.Credentials
	(*Subsystem)(nil),                   // 7: v1.Subsystem
	(*BMCInfo)(nil),                     // 8: v1.BMCInfo
	(*NVOSInfo)(nil),                    // 9: v1.NVOSInfo
	(*Chassis)(nil),                     // 10: v1.Chassis
	(*NVSwitchTray)(nil),                // 11: v1.NVSwitchTray
	(*RegisterNVSwitchRequest)(nil),     // 12: v1.RegisterNVSwitchRequest
	(*RegisterNVSwitchesRequest)(nil),   // 13: v1.RegisterNVSwitchesRequest
	(*RegisterNVSwitchResponse)(nil),    // 14: v1.RegisterNVSwitchResponse
	(*RegisterNVSwitchesResponse)(nil),  // 15: v1.RegisterNVSwitchesResponse
	(*NVSwitchRequest)(nil),             // 16: v1.NVSwitchRequest
	(*NVSwitchResponse)(nil),            // 17: v1.NVSwitchResponse
	(*PowerTarget)(nil),                 // 18: v1.PowerTarget
	(*FirmwareTarget)(nil),              // 19: v1.FirmwareTarget
	(*PowerControlRequest)(nil),         // 20: v1.PowerControlRequest
	(*PowerControlResponse)(nil),        // 21: v1.PowerControlResponse
	(*GetNVSwitchesResponse)(nil),       // 22: v1.GetNVSwitchesResponse
	(*FirmwareBundle)(nil),              // 23: v1.FirmwareBundle
	(*ComponentInfo)(nil),               // 24: v1.ComponentInfo
	(*ListBundlesResponse)(nil),         // 25: v1.ListBundlesResponse
	(*QueueUpdateRequest)(nil),          // 26: v1.QueueUpdateRequest
	(*QueueUpdateResponse)(nil),         // 27: v1.QueueUpdateResponse
	(*QueueUpdatesRequest)(nil),         // 28: v1.QueueUpdatesRequest
	(*QueueUpdatesResponse)(nil),        // 29: v1.QueueUpdatesResponse
	(*QueueUpdateResult)(nil),           // 30: v1.QueueUpdateResult
	(*GetUpdateRequest)(nil),            // 31: v1.GetUpdateRequest
	(*GetUpdateResponse)(nil),           // 32: v1.GetUpdateResponse
	(*GetUpdatesForSwitchRequest)(nil),  // 33: v1.GetUpdatesForSwitchRequest
	(*GetUpdatesForSwitchResponse)(nil), // 34: v1.GetUpdatesForSwitchResponse
	(*GetAllUpdatesResponse)(nil),       // 35: v1.GetAllUpdatesResponse
	(*CancelUpdateRequest)(nil),         // 36: v1.CancelUpdateRequest
	(*CancelUpdateResponse)(nil),        // 37: v1.CancelUpdateResponse
	(*FirmwareUpdateInfo)(nil),          // 38: v1.FirmwareUpdateInfo
	(*timestamppb.Timestamp)(nil),       // 39: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 40: google.protobuf.Empty
}
var file_internal_proto_v1_nvswitch_manager_proto_depIdxs = []int32{
	6,  // 0: v1.Subsystem.credentials:type_name -> v1.Credentials
	0,  // 1: v1.NVSwitchTray.vendor:type_name -> v1.Vendor
	8,  // 2: v1.NVSwitchTray.bmc:type_name -> v1.BMCInfo
	9,  // 3: v1.NVSwitchTray.nvos:type_name -> v1.NVOSInfo
	10, // 4: v1.NVSwitchTray.chassis:type_name -> v1.Chassis
	0,  // 5: v1.RegisterNVSwitchRequest.vendor:type_name -> v1.Vendor
	7,  // 6: v1.RegisterNVSwitchRequest.bmc:type_name -> v1.Subsystem
	7,  // 7: v1.RegisterNVSwitchRequest.nvos:type_name -> v1.Subsystem
	12, // 8: v1.RegisterNVSwitchesRequest.registration_requests:type_name -> v1.RegisterNVSwitchRequest
	39, // 9: v1.RegisterNVSwitchResponse.created:type_name -> google.protobuf.Timestamp
	1,  // 10: v1.RegisterNVSwitchResponse.status:type_name -> v1.StatusCode
	14, // 11: v1.RegisterNVSwitchesResponse.responses:type_name -> v1.RegisterNVSwitchResponse
	1,  // 12: v1.NVSwitchResponse.status:type_name -> v1.StatusCode
	6,  // 13: v1.PowerTarget.bmc_credentials:type_name -> v1.Credentials
	6,  // 14: v1.FirmwareTarget.bmc_credentials:type_name -> v1.Credentials
	6,  // 15: v1.FirmwareTarget.nvos_credentials:type_name -> v1.Credentials
	0,  // 16: v1.FirmwareTarget.vendor:type_name -> v1.Vendor
	2,  // 17: v1.PowerControlRequest.action:type_name -> v1.PowerAction
	18, // 18: v1.PowerControlRequest.targets:type_name -> v1.PowerTarget
	17, // 19: v1.PowerControlResponse.responses:type_name -> v1.NVSwitchResponse
	11, // 20: v1.GetNVSwitchesResponse.nvswitches:type_name -> v1.NVSwitchTray
	24, // 21: v1.FirmwareBundle.components:type_name -> v1.ComponentInfo
	23, // 22: v1.ListBundlesResponse.bundles:type_name -> v1.FirmwareBundle
	3,  // 23: v1.QueueUpdateRequest.components:type_name -> v1.NVSwitchComponent
	38, // 24: v1.QueueUpdateResponse.updates:type_name -> v1.FirmwareUpdateInfo
	3,  // 25: v1.QueueUpdatesRequest.components:type_name -> v1.NVSwitchComponent
	19, // 26: v1.QueueUpdatesRequest.targets:type_name -> v1.FirmwareTarget
	30, // 27: v1.QueueUpdatesResponse.results:type_name -> v1.QueueUpdateResult
	1,  // 28: v1.QueueUpdateResult.status:type_name -> v1.StatusCode
	38, // 29: v1.QueueUpdateResult.updates:type_name -> v1.FirmwareUpdateInfo
	38, // 30: v1.GetUpdateResponse.update:type_name -> v1.FirmwareUpdateInfo
	38, // 31: v1.GetUpdatesForSwitchResponse.updates:type_name -> v1.FirmwareUpdateInfo
	38, // 32: v1.GetAllUpdatesResponse.updates:type_name -> v1.FirmwareUpdateInfo
	3,  // 33: v1.FirmwareUpdateInfo.component:type_name -> v1.NVSwitchComponent
	4,  // 34: v1.FirmwareUpdateInfo.strategy:type_name -> v1.UpdateStrategy
	5,  // 35: v1.FirmwareUpdateInfo.state:type_name -> v1.UpdateState
	39, // 36: v1.FirmwareUpdateInfo.created_at:type_name -> google.protobuf.Timestamp
	39, // 37: v1.FirmwareUpdateInfo.updated_at:type_name -> google.protobuf.Timestamp
	13, // 38: v1.NVSwitchManager.RegisterNVSwitches:input_type -> v1.RegisterNVSwitchesRequest
	16, // 39: v1.NVSwitchManager.GetNVSwitches:input_type -> v1.NVSwitchRequest
	40, // 40: v1.NVSwitchManager.ListBundles:input_type -> google.protobuf.Empty
	26, // 41: v1.NVSwitchManager.QueueUpdate:input_type -> v1.QueueUpdateRequest
	28, // 42: v1.NVSwitchManager.QueueUpdates:input_type -> v1.QueueUpdatesRequest
	31, // 43: v1.NVSwitchManager.GetUpdate:input_type -> v1.GetUpdateRequest
	33, // 44: v1.NVSwitchManager.GetUpdatesForSwitch:input_type -> v1.GetUpdatesForSwitchRequest
	40, // 45: v1.NVSwitchManager.GetAllUpdates:input_type -> google.protobuf.Empty
	36, // 46: v1.NVSwitchManager.CancelUpdate:input_type -> v1.CancelUpdateRequest
	20, // 47: v1.NVSwitchManager.PowerControl:input_type -> v1.PowerControlRequest
	15, // 48: v1.NVSwitchManager.RegisterNVSwitches:output_type -> v1.RegisterNVSwitchesResponse
	22, // 49: v1.NVSwitchManager.GetNVSwitches:output_type -> v1.GetNVSwitchesResponse
	25, // 50: v1.NVSwitchManager.ListBundles:output_type -> v1.ListBundlesResponse
	27, // 51: v1.NVSwitchManager.QueueUpdate:output_type -> v1.QueueUpdateResponse
	29, // 52: v1.NVSwitchManager.QueueUpdates:output_type -> v1.QueueUpdatesResponse
	32, // 53: v1.NVSwitchManager.GetUpdate:output_type -> v1.GetUpdateResponse
	34, // 54: v1.NVSwitchManager.GetUpdatesForSwitch:output_type -> v1.GetUpdatesForSwitchResponse
	35, // 55: v1.NVSwitchManager.GetAllUpdates:output_type -> v1.GetAllUpdatesResponse
	37, // 56: v1.NVSwitchManager.CancelUpdate:output_type -> v1.CancelUpdateResponse
	21, // 57: v1.NVSwitchManager.PowerControl:output_type -> v1.PowerControlResponse
	48, // [48:58] is the sub-list for method output_type
	38, // [38:48] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_internal_proto_v1_nvswitch_manager_proto_init() }
func file_internal_proto_v1_nvswitch_manager_proto_init() {
	if File_internal_proto_v1_nvswitch_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v1_nvswitch_manager_proto_rawDesc), len(file_internal_proto_v1_nvswitch_manager_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_v1_nvswitch_manager_proto_goTypes,
		DependencyIndexes: file_internal_proto_v1_nvswitch_manager_proto_depIdxs,
		EnumInfos:         file_internal_proto_v1_nvswitch_manager_proto_enumTypes,
		MessageInfos:      file_internal_proto_v1_nvswitch_manager_proto_msgTypes,
	}.Build()
	File_internal_proto_v1_nvswitch_manager_proto = out.File
	file_internal_proto_v1_nvswitch_manager_proto_goTypes = nil
	file_internal_proto_v1_nvswitch_manager_proto_depIdxs = nil
}
