/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BMCCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BMCCredential{}

// BMCCredential BMC credential metadata returned after create or update. Password is never returned.
type BMCCredential struct {
	// ID of the Site where the credential is stored.
	SiteId string `json:"siteId"`
	// Which BMC credential was stored.
	Kind string `json:"kind"`
	// Optional username; Core defaults to \"root\" for bmc-root when omitted.
	Username *string `json:"username,omitempty"`
	// BMC MAC address. Required for kind bmc-root, ignored for site-wide-root.
	MacAddress *string `json:"macAddress,omitempty"`
}

type _BMCCredential BMCCredential

// NewBMCCredential instantiates a new BMCCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBMCCredential(siteId string, kind string) *BMCCredential {
	this := BMCCredential{}
	this.SiteId = siteId
	this.Kind = kind
	return &this
}

// NewBMCCredentialWithDefaults instantiates a new BMCCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBMCCredentialWithDefaults() *BMCCredential {
	this := BMCCredential{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *BMCCredential) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *BMCCredential) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *BMCCredential) SetSiteId(v string) {
	o.SiteId = v
}

// GetKind returns the Kind field value
func (o *BMCCredential) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *BMCCredential) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *BMCCredential) SetKind(v string) {
	o.Kind = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *BMCCredential) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BMCCredential) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *BMCCredential) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *BMCCredential) SetUsername(v string) {
	o.Username = &v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise.
func (o *BMCCredential) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress) {
		var ret string
		return ret
	}
	return *o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BMCCredential) GetMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MacAddress) {
		return nil, false
	}
	return o.MacAddress, true
}

// HasMacAddress returns a boolean if a field has been set.
func (o *BMCCredential) HasMacAddress() bool {
	if o != nil && !IsNil(o.MacAddress) {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given string and assigns it to the MacAddress field.
func (o *BMCCredential) SetMacAddress(v string) {
	o.MacAddress = &v
}

func (o BMCCredential) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BMCCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["kind"] = o.Kind
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.MacAddress) {
		toSerialize["macAddress"] = o.MacAddress
	}
	return toSerialize, nil
}

func (o *BMCCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBMCCredential := _BMCCredential{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBMCCredential)

	if err != nil {
		return err
	}

	*o = BMCCredential(varBMCCredential)

	return err
}

type NullableBMCCredential struct {
	value *BMCCredential
	isSet bool
}

func (v NullableBMCCredential) Get() *BMCCredential {
	return v.value
}

func (v *NullableBMCCredential) Set(val *BMCCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableBMCCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableBMCCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBMCCredential(val *BMCCredential) *NullableBMCCredential {
	return &NullableBMCCredential{value: val, isSet: true}
}

func (v NullableBMCCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBMCCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
