// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchBringUpRackRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchBringUpRackRequest{}

// BatchBringUpRackRequest Request body for batch rack bring up operations
type BatchBringUpRackRequest struct {
	// ID of the Site
	SiteId string `json:"siteId"`
	// Filter that selects Racks targeted for bring-up
	Filter *RackFilter `json:"filter,omitempty"`
	// Optional description for the bring up operation
	Description *string `json:"description,omitempty"`
	// Optional Operation Rule UUID. When set, pins every bring-up task spawned by this batch to the named rule and overrides Flow's default rule resolution.
	RuleId *string `json:"ruleId,omitempty"`
	// When true, proceed even if one or more target components (or hosts on the owning rack) are reported as not ready by their persisted status. Intended for operator-supervised maintenance.
	OverrideReadinessCheck *bool `json:"overrideReadinessCheck,omitempty"`
}

type _BatchBringUpRackRequest BatchBringUpRackRequest

// NewBatchBringUpRackRequest instantiates a new BatchBringUpRackRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchBringUpRackRequest(siteId string) *BatchBringUpRackRequest {
	this := BatchBringUpRackRequest{}
	this.SiteId = siteId
	var overrideReadinessCheck bool = false
	this.OverrideReadinessCheck = &overrideReadinessCheck
	return &this
}

// NewBatchBringUpRackRequestWithDefaults instantiates a new BatchBringUpRackRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchBringUpRackRequestWithDefaults() *BatchBringUpRackRequest {
	this := BatchBringUpRackRequest{}
	var overrideReadinessCheck bool = false
	this.OverrideReadinessCheck = &overrideReadinessCheck
	return &this
}

// GetSiteId returns the SiteId field value
func (o *BatchBringUpRackRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *BatchBringUpRackRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *BatchBringUpRackRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *BatchBringUpRackRequest) GetFilter() RackFilter {
	if o == nil || IsNil(o.Filter) {
		var ret RackFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchBringUpRackRequest) GetFilterOk() (*RackFilter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *BatchBringUpRackRequest) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given RackFilter and assigns it to the Filter field.
func (o *BatchBringUpRackRequest) SetFilter(v RackFilter) {
	o.Filter = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BatchBringUpRackRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchBringUpRackRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BatchBringUpRackRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BatchBringUpRackRequest) SetDescription(v string) {
	o.Description = &v
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *BatchBringUpRackRequest) GetRuleId() string {
	if o == nil || IsNil(o.RuleId) {
		var ret string
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchBringUpRackRequest) GetRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RuleId) {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *BatchBringUpRackRequest) HasRuleId() bool {
	if o != nil && !IsNil(o.RuleId) {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given string and assigns it to the RuleId field.
func (o *BatchBringUpRackRequest) SetRuleId(v string) {
	o.RuleId = &v
}

// GetOverrideReadinessCheck returns the OverrideReadinessCheck field value if set, zero value otherwise.
func (o *BatchBringUpRackRequest) GetOverrideReadinessCheck() bool {
	if o == nil || IsNil(o.OverrideReadinessCheck) {
		var ret bool
		return ret
	}
	return *o.OverrideReadinessCheck
}

// GetOverrideReadinessCheckOk returns a tuple with the OverrideReadinessCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchBringUpRackRequest) GetOverrideReadinessCheckOk() (*bool, bool) {
	if o == nil || IsNil(o.OverrideReadinessCheck) {
		return nil, false
	}
	return o.OverrideReadinessCheck, true
}

// HasOverrideReadinessCheck returns a boolean if a field has been set.
func (o *BatchBringUpRackRequest) HasOverrideReadinessCheck() bool {
	if o != nil && !IsNil(o.OverrideReadinessCheck) {
		return true
	}

	return false
}

// SetOverrideReadinessCheck gets a reference to the given bool and assigns it to the OverrideReadinessCheck field.
func (o *BatchBringUpRackRequest) SetOverrideReadinessCheck(v bool) {
	o.OverrideReadinessCheck = &v
}

func (o BatchBringUpRackRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchBringUpRackRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.RuleId) {
		toSerialize["ruleId"] = o.RuleId
	}
	if !IsNil(o.OverrideReadinessCheck) {
		toSerialize["overrideReadinessCheck"] = o.OverrideReadinessCheck
	}
	return toSerialize, nil
}

func (o *BatchBringUpRackRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchBringUpRackRequest := _BatchBringUpRackRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchBringUpRackRequest)

	if err != nil {
		return err
	}

	*o = BatchBringUpRackRequest(varBatchBringUpRackRequest)

	return err
}

type NullableBatchBringUpRackRequest struct {
	value *BatchBringUpRackRequest
	isSet bool
}

func (v NullableBatchBringUpRackRequest) Get() *BatchBringUpRackRequest {
	return v.value
}

func (v *NullableBatchBringUpRackRequest) Set(val *BatchBringUpRackRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchBringUpRackRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchBringUpRackRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchBringUpRackRequest(val *BatchBringUpRackRequest) *NullableBatchBringUpRackRequest {
	return &NullableBatchBringUpRackRequest{value: val, isSet: true}
}

func (v NullableBatchBringUpRackRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchBringUpRackRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
