// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the ExpectedPowerShelfUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedPowerShelfUpdateRequest{}

// ExpectedPowerShelfUpdateRequest Request data to update an existing Expected Power Shelf.  Note: BMC credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedPowerShelfUpdateRequest struct {
	// ID of the Expected Power Shelf to update (ignored for single update, used for identification in batch operations).
	Id NullableString `json:"id,omitempty"`
	// MAC address of the Expected Power Shelf's BMC (Baseboard Management Controller)
	BmcMacAddress NullableString `json:"bmcMacAddress,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Username for accessing the Expected Power Shelf's BMC
	DefaultBmcUsername NullableString `json:"defaultBmcUsername,omitempty"`
	// Password for accessing the Expected Power Shelf's BMC
	DefaultBmcPassword NullableString `json:"defaultBmcPassword,omitempty"`
	// Serial number of the Expected Power Shelf
	ShelfSerialNumber NullableString `json:"shelfSerialNumber,omitempty"`
	// Optional BMC IP address (IPv4 or IPv6). When set, pre-allocates a reserved IP for the BMC.
	BmcIpAddress NullableString `json:"bmcIpAddress,omitempty"`
	// Optional rack identifier for this component
	RackId NullableString `json:"rackId,omitempty"`
	// Display name for this component
	Name NullableString `json:"name,omitempty"`
	// Manufacturer of this component
	Manufacturer NullableString `json:"manufacturer,omitempty"`
	// Model of this component
	Model NullableString `json:"model,omitempty"`
	// Description of this component
	Description NullableString `json:"description,omitempty"`
	// Slot ID within the rack
	SlotId NullableInt32 `json:"slotId,omitempty"`
	// Tray index within the rack
	TrayIdx NullableInt32 `json:"trayIdx,omitempty"`
	// Host ID within the tray
	HostId NullableInt32 `json:"hostId,omitempty"`
	// User-defined key-value pairs for organizing and categorizing Expected Power Shelves
	Labels map[string]string `json:"labels,omitempty"`
}

// NewExpectedPowerShelfUpdateRequest instantiates a new ExpectedPowerShelfUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedPowerShelfUpdateRequest() *ExpectedPowerShelfUpdateRequest {
	this := ExpectedPowerShelfUpdateRequest{}
	return &this
}

// NewExpectedPowerShelfUpdateRequestWithDefaults instantiates a new ExpectedPowerShelfUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedPowerShelfUpdateRequestWithDefaults() *ExpectedPowerShelfUpdateRequest {
	this := ExpectedPowerShelfUpdateRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ExpectedPowerShelfUpdateRequest) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetId() {
	o.Id.Unset()
}

// GetBmcMacAddress returns the BmcMacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetBmcMacAddress() string {
	if o == nil || IsNil(o.BmcMacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.BmcMacAddress.Get()
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetBmcMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcMacAddress.Get(), o.BmcMacAddress.IsSet()
}

// HasBmcMacAddress returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasBmcMacAddress() bool {
	if o != nil && o.BmcMacAddress.IsSet() {
		return true
	}

	return false
}

// SetBmcMacAddress gets a reference to the given NullableString and assigns it to the BmcMacAddress field.
func (o *ExpectedPowerShelfUpdateRequest) SetBmcMacAddress(v string) {
	o.BmcMacAddress.Set(&v)
}

// SetBmcMacAddressNil sets the value for BmcMacAddress to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetBmcMacAddressNil() {
	o.BmcMacAddress.Set(nil)
}

// UnsetBmcMacAddress ensures that no value is present for BmcMacAddress, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetBmcMacAddress() {
	o.BmcMacAddress.Unset()
}

// GetDefaultBmcUsername returns the DefaultBmcUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetDefaultBmcUsername() string {
	if o == nil || IsNil(o.DefaultBmcUsername.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcUsername.Get()
}

// GetDefaultBmcUsernameOk returns a tuple with the DefaultBmcUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetDefaultBmcUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcUsername.Get(), o.DefaultBmcUsername.IsSet()
}

// HasDefaultBmcUsername returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasDefaultBmcUsername() bool {
	if o != nil && o.DefaultBmcUsername.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcUsername gets a reference to the given NullableString and assigns it to the DefaultBmcUsername field.
func (o *ExpectedPowerShelfUpdateRequest) SetDefaultBmcUsername(v string) {
	o.DefaultBmcUsername.Set(&v)
}

// SetDefaultBmcUsernameNil sets the value for DefaultBmcUsername to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetDefaultBmcUsernameNil() {
	o.DefaultBmcUsername.Set(nil)
}

// UnsetDefaultBmcUsername ensures that no value is present for DefaultBmcUsername, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetDefaultBmcUsername() {
	o.DefaultBmcUsername.Unset()
}

// GetDefaultBmcPassword returns the DefaultBmcPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetDefaultBmcPassword() string {
	if o == nil || IsNil(o.DefaultBmcPassword.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcPassword.Get()
}

// GetDefaultBmcPasswordOk returns a tuple with the DefaultBmcPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetDefaultBmcPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcPassword.Get(), o.DefaultBmcPassword.IsSet()
}

// HasDefaultBmcPassword returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasDefaultBmcPassword() bool {
	if o != nil && o.DefaultBmcPassword.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcPassword gets a reference to the given NullableString and assigns it to the DefaultBmcPassword field.
func (o *ExpectedPowerShelfUpdateRequest) SetDefaultBmcPassword(v string) {
	o.DefaultBmcPassword.Set(&v)
}

// SetDefaultBmcPasswordNil sets the value for DefaultBmcPassword to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetDefaultBmcPasswordNil() {
	o.DefaultBmcPassword.Set(nil)
}

// UnsetDefaultBmcPassword ensures that no value is present for DefaultBmcPassword, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetDefaultBmcPassword() {
	o.DefaultBmcPassword.Unset()
}

// GetShelfSerialNumber returns the ShelfSerialNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetShelfSerialNumber() string {
	if o == nil || IsNil(o.ShelfSerialNumber.Get()) {
		var ret string
		return ret
	}
	return *o.ShelfSerialNumber.Get()
}

// GetShelfSerialNumberOk returns a tuple with the ShelfSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetShelfSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShelfSerialNumber.Get(), o.ShelfSerialNumber.IsSet()
}

// HasShelfSerialNumber returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasShelfSerialNumber() bool {
	if o != nil && o.ShelfSerialNumber.IsSet() {
		return true
	}

	return false
}

// SetShelfSerialNumber gets a reference to the given NullableString and assigns it to the ShelfSerialNumber field.
func (o *ExpectedPowerShelfUpdateRequest) SetShelfSerialNumber(v string) {
	o.ShelfSerialNumber.Set(&v)
}

// SetShelfSerialNumberNil sets the value for ShelfSerialNumber to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetShelfSerialNumberNil() {
	o.ShelfSerialNumber.Set(nil)
}

// UnsetShelfSerialNumber ensures that no value is present for ShelfSerialNumber, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetShelfSerialNumber() {
	o.ShelfSerialNumber.Unset()
}

// GetBmcIpAddress returns the BmcIpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetBmcIpAddress() string {
	if o == nil || IsNil(o.BmcIpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.BmcIpAddress.Get()
}

// GetBmcIpAddressOk returns a tuple with the BmcIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetBmcIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcIpAddress.Get(), o.BmcIpAddress.IsSet()
}

// HasBmcIpAddress returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasBmcIpAddress() bool {
	if o != nil && o.BmcIpAddress.IsSet() {
		return true
	}

	return false
}

// SetBmcIpAddress gets a reference to the given NullableString and assigns it to the BmcIpAddress field.
func (o *ExpectedPowerShelfUpdateRequest) SetBmcIpAddress(v string) {
	o.BmcIpAddress.Set(&v)
}

// SetBmcIpAddressNil sets the value for BmcIpAddress to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetBmcIpAddressNil() {
	o.BmcIpAddress.Set(nil)
}

// UnsetBmcIpAddress ensures that no value is present for BmcIpAddress, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetBmcIpAddress() {
	o.BmcIpAddress.Unset()
}

// GetRackId returns the RackId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetRackId() string {
	if o == nil || IsNil(o.RackId.Get()) {
		var ret string
		return ret
	}
	return *o.RackId.Get()
}

// GetRackIdOk returns a tuple with the RackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetRackIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RackId.Get(), o.RackId.IsSet()
}

// HasRackId returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasRackId() bool {
	if o != nil && o.RackId.IsSet() {
		return true
	}

	return false
}

// SetRackId gets a reference to the given NullableString and assigns it to the RackId field.
func (o *ExpectedPowerShelfUpdateRequest) SetRackId(v string) {
	o.RackId.Set(&v)
}

// SetRackIdNil sets the value for RackId to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetRackIdNil() {
	o.RackId.Set(nil)
}

// UnsetRackId ensures that no value is present for RackId, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetRackId() {
	o.RackId.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ExpectedPowerShelfUpdateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetName() {
	o.Name.Unset()
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer.Get()) {
		var ret string
		return ret
	}
	return *o.Manufacturer.Get()
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Manufacturer.Get(), o.Manufacturer.IsSet()
}

// HasManufacturer returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasManufacturer() bool {
	if o != nil && o.Manufacturer.IsSet() {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given NullableString and assigns it to the Manufacturer field.
func (o *ExpectedPowerShelfUpdateRequest) SetManufacturer(v string) {
	o.Manufacturer.Set(&v)
}

// SetManufacturerNil sets the value for Manufacturer to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetManufacturerNil() {
	o.Manufacturer.Set(nil)
}

// UnsetManufacturer ensures that no value is present for Manufacturer, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetManufacturer() {
	o.Manufacturer.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *ExpectedPowerShelfUpdateRequest) SetModel(v string) {
	o.Model.Set(&v)
}

// SetModelNil sets the value for Model to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetModel() {
	o.Model.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ExpectedPowerShelfUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetSlotId returns the SlotId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetSlotId() int32 {
	if o == nil || IsNil(o.SlotId.Get()) {
		var ret int32
		return ret
	}
	return *o.SlotId.Get()
}

// GetSlotIdOk returns a tuple with the SlotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetSlotIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlotId.Get(), o.SlotId.IsSet()
}

// HasSlotId returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasSlotId() bool {
	if o != nil && o.SlotId.IsSet() {
		return true
	}

	return false
}

// SetSlotId gets a reference to the given NullableInt32 and assigns it to the SlotId field.
func (o *ExpectedPowerShelfUpdateRequest) SetSlotId(v int32) {
	o.SlotId.Set(&v)
}

// SetSlotIdNil sets the value for SlotId to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetSlotIdNil() {
	o.SlotId.Set(nil)
}

// UnsetSlotId ensures that no value is present for SlotId, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetSlotId() {
	o.SlotId.Unset()
}

// GetTrayIdx returns the TrayIdx field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetTrayIdx() int32 {
	if o == nil || IsNil(o.TrayIdx.Get()) {
		var ret int32
		return ret
	}
	return *o.TrayIdx.Get()
}

// GetTrayIdxOk returns a tuple with the TrayIdx field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetTrayIdxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrayIdx.Get(), o.TrayIdx.IsSet()
}

// HasTrayIdx returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasTrayIdx() bool {
	if o != nil && o.TrayIdx.IsSet() {
		return true
	}

	return false
}

// SetTrayIdx gets a reference to the given NullableInt32 and assigns it to the TrayIdx field.
func (o *ExpectedPowerShelfUpdateRequest) SetTrayIdx(v int32) {
	o.TrayIdx.Set(&v)
}

// SetTrayIdxNil sets the value for TrayIdx to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetTrayIdxNil() {
	o.TrayIdx.Set(nil)
}

// UnsetTrayIdx ensures that no value is present for TrayIdx, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetTrayIdx() {
	o.TrayIdx.Unset()
}

// GetHostId returns the HostId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetHostId() int32 {
	if o == nil || IsNil(o.HostId.Get()) {
		var ret int32
		return ret
	}
	return *o.HostId.Get()
}

// GetHostIdOk returns a tuple with the HostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetHostIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.HostId.Get(), o.HostId.IsSet()
}

// HasHostId returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasHostId() bool {
	if o != nil && o.HostId.IsSet() {
		return true
	}

	return false
}

// SetHostId gets a reference to the given NullableInt32 and assigns it to the HostId field.
func (o *ExpectedPowerShelfUpdateRequest) SetHostId(v int32) {
	o.HostId.Set(&v)
}

// SetHostIdNil sets the value for HostId to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetHostIdNil() {
	o.HostId.Set(nil)
}

// UnsetHostId ensures that no value is present for HostId, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetHostId() {
	o.HostId.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedPowerShelfUpdateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedPowerShelfUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedPowerShelfUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedPowerShelfUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.BmcMacAddress.IsSet() {
		toSerialize["bmcMacAddress"] = o.BmcMacAddress.Get()
	}
	if o.DefaultBmcUsername.IsSet() {
		toSerialize["defaultBmcUsername"] = o.DefaultBmcUsername.Get()
	}
	if o.DefaultBmcPassword.IsSet() {
		toSerialize["defaultBmcPassword"] = o.DefaultBmcPassword.Get()
	}
	if o.ShelfSerialNumber.IsSet() {
		toSerialize["shelfSerialNumber"] = o.ShelfSerialNumber.Get()
	}
	if o.BmcIpAddress.IsSet() {
		toSerialize["bmcIpAddress"] = o.BmcIpAddress.Get()
	}
	if o.RackId.IsSet() {
		toSerialize["rackId"] = o.RackId.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Manufacturer.IsSet() {
		toSerialize["manufacturer"] = o.Manufacturer.Get()
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.SlotId.IsSet() {
		toSerialize["slotId"] = o.SlotId.Get()
	}
	if o.TrayIdx.IsSet() {
		toSerialize["trayIdx"] = o.TrayIdx.Get()
	}
	if o.HostId.IsSet() {
		toSerialize["hostId"] = o.HostId.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableExpectedPowerShelfUpdateRequest struct {
	value *ExpectedPowerShelfUpdateRequest
	isSet bool
}

func (v NullableExpectedPowerShelfUpdateRequest) Get() *ExpectedPowerShelfUpdateRequest {
	return v.value
}

func (v *NullableExpectedPowerShelfUpdateRequest) Set(val *ExpectedPowerShelfUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedPowerShelfUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedPowerShelfUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedPowerShelfUpdateRequest(val *ExpectedPowerShelfUpdateRequest) *NullableExpectedPowerShelfUpdateRequest {
	return &NullableExpectedPowerShelfUpdateRequest{value: val, isSet: true}
}

func (v NullableExpectedPowerShelfUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedPowerShelfUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
