// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the ExpectedSwitch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedSwitch{}

// ExpectedSwitch An Expected Switch represents a network switch that is expected to be discovered at a site, with hardware identifiers and metadata.  Note: BMC and NvOS credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedSwitch struct {
	// Unique identifier for the Expected Switch
	Id *string `json:"id,omitempty"`
	// ID of the site the Expected Switch belongs to
	SiteId *string `json:"siteId,omitempty"`
	// MAC address of the Expected Switch's BMC (Baseboard Management Controller)
	BmcMacAddress *string `json:"bmcMacAddress,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Serial number of the Expected Switch
	SwitchSerialNumber *string `json:"switchSerialNumber,omitempty"`
	// Optional rack identifier for this component
	RackId NullableString `json:"rackId,omitempty"`
	// Optional BMC IP address (IPv4 or IPv6). When set, pre-allocates a reserved IP for the BMC.
	BmcIpAddress NullableString `json:"bmcIpAddress,omitempty"`
	// Display name for this component
	Name NullableString `json:"name,omitempty"`
	// Manufacturer of this component
	Manufacturer NullableString `json:"manufacturer,omitempty"`
	// Model of this component
	Model NullableString `json:"model,omitempty"`
	// Description of this component
	Description NullableString `json:"description,omitempty"`
	// Slot ID within the rack
	SlotId NullableInt32 `json:"slotId,omitempty"`
	// Tray index within the rack
	TrayIdx NullableInt32 `json:"trayIdx,omitempty"`
	// Host ID within the tray
	HostId NullableInt32 `json:"hostId,omitempty"`
	// User-defined key-value pairs for organizing and categorizing Expected Switches
	Labels map[string]string `json:"labels,omitempty"`
	// ISO 8601 datetime when the Expected Switch was created
	Created *time.Time `json:"created,omitempty"`
	// ISO 8601 datetime when the Expected Switch was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewExpectedSwitch instantiates a new ExpectedSwitch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedSwitch() *ExpectedSwitch {
	this := ExpectedSwitch{}
	return &this
}

// NewExpectedSwitchWithDefaults instantiates a new ExpectedSwitch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedSwitchWithDefaults() *ExpectedSwitch {
	this := ExpectedSwitch{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ExpectedSwitch) SetId(v string) {
	o.Id = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *ExpectedSwitch) SetSiteId(v string) {
	o.SiteId = &v
}

// GetBmcMacAddress returns the BmcMacAddress field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetBmcMacAddress() string {
	if o == nil || IsNil(o.BmcMacAddress) {
		var ret string
		return ret
	}
	return *o.BmcMacAddress
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetBmcMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.BmcMacAddress) {
		return nil, false
	}
	return o.BmcMacAddress, true
}

// HasBmcMacAddress returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasBmcMacAddress() bool {
	if o != nil && !IsNil(o.BmcMacAddress) {
		return true
	}

	return false
}

// SetBmcMacAddress gets a reference to the given string and assigns it to the BmcMacAddress field.
func (o *ExpectedSwitch) SetBmcMacAddress(v string) {
	o.BmcMacAddress = &v
}

// GetSwitchSerialNumber returns the SwitchSerialNumber field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetSwitchSerialNumber() string {
	if o == nil || IsNil(o.SwitchSerialNumber) {
		var ret string
		return ret
	}
	return *o.SwitchSerialNumber
}

// GetSwitchSerialNumberOk returns a tuple with the SwitchSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetSwitchSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SwitchSerialNumber) {
		return nil, false
	}
	return o.SwitchSerialNumber, true
}

// HasSwitchSerialNumber returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasSwitchSerialNumber() bool {
	if o != nil && !IsNil(o.SwitchSerialNumber) {
		return true
	}

	return false
}

// SetSwitchSerialNumber gets a reference to the given string and assigns it to the SwitchSerialNumber field.
func (o *ExpectedSwitch) SetSwitchSerialNumber(v string) {
	o.SwitchSerialNumber = &v
}

// GetRackId returns the RackId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitch) GetRackId() string {
	if o == nil || IsNil(o.RackId.Get()) {
		var ret string
		return ret
	}
	return *o.RackId.Get()
}

// GetRackIdOk returns a tuple with the RackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitch) GetRackIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RackId.Get(), o.RackId.IsSet()
}

// HasRackId returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasRackId() bool {
	if o != nil && o.RackId.IsSet() {
		return true
	}

	return false
}

// SetRackId gets a reference to the given NullableString and assigns it to the RackId field.
func (o *ExpectedSwitch) SetRackId(v string) {
	o.RackId.Set(&v)
}

// SetRackIdNil sets the value for RackId to be an explicit nil
func (o *ExpectedSwitch) SetRackIdNil() {
	o.RackId.Set(nil)
}

// UnsetRackId ensures that no value is present for RackId, not even an explicit nil
func (o *ExpectedSwitch) UnsetRackId() {
	o.RackId.Unset()
}

// GetBmcIpAddress returns the BmcIpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitch) GetBmcIpAddress() string {
	if o == nil || IsNil(o.BmcIpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.BmcIpAddress.Get()
}

// GetBmcIpAddressOk returns a tuple with the BmcIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitch) GetBmcIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcIpAddress.Get(), o.BmcIpAddress.IsSet()
}

// HasBmcIpAddress returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasBmcIpAddress() bool {
	if o != nil && o.BmcIpAddress.IsSet() {
		return true
	}

	return false
}

// SetBmcIpAddress gets a reference to the given NullableString and assigns it to the BmcIpAddress field.
func (o *ExpectedSwitch) SetBmcIpAddress(v string) {
	o.BmcIpAddress.Set(&v)
}

// SetBmcIpAddressNil sets the value for BmcIpAddress to be an explicit nil
func (o *ExpectedSwitch) SetBmcIpAddressNil() {
	o.BmcIpAddress.Set(nil)
}

// UnsetBmcIpAddress ensures that no value is present for BmcIpAddress, not even an explicit nil
func (o *ExpectedSwitch) UnsetBmcIpAddress() {
	o.BmcIpAddress.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitch) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitch) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ExpectedSwitch) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ExpectedSwitch) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ExpectedSwitch) UnsetName() {
	o.Name.Unset()
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitch) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer.Get()) {
		var ret string
		return ret
	}
	return *o.Manufacturer.Get()
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitch) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Manufacturer.Get(), o.Manufacturer.IsSet()
}

// HasManufacturer returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasManufacturer() bool {
	if o != nil && o.Manufacturer.IsSet() {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given NullableString and assigns it to the Manufacturer field.
func (o *ExpectedSwitch) SetManufacturer(v string) {
	o.Manufacturer.Set(&v)
}

// SetManufacturerNil sets the value for Manufacturer to be an explicit nil
func (o *ExpectedSwitch) SetManufacturerNil() {
	o.Manufacturer.Set(nil)
}

// UnsetManufacturer ensures that no value is present for Manufacturer, not even an explicit nil
func (o *ExpectedSwitch) UnsetManufacturer() {
	o.Manufacturer.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitch) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitch) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *ExpectedSwitch) SetModel(v string) {
	o.Model.Set(&v)
}

// SetModelNil sets the value for Model to be an explicit nil
func (o *ExpectedSwitch) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *ExpectedSwitch) UnsetModel() {
	o.Model.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitch) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitch) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ExpectedSwitch) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ExpectedSwitch) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ExpectedSwitch) UnsetDescription() {
	o.Description.Unset()
}

// GetSlotId returns the SlotId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitch) GetSlotId() int32 {
	if o == nil || IsNil(o.SlotId.Get()) {
		var ret int32
		return ret
	}
	return *o.SlotId.Get()
}

// GetSlotIdOk returns a tuple with the SlotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitch) GetSlotIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlotId.Get(), o.SlotId.IsSet()
}

// HasSlotId returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasSlotId() bool {
	if o != nil && o.SlotId.IsSet() {
		return true
	}

	return false
}

// SetSlotId gets a reference to the given NullableInt32 and assigns it to the SlotId field.
func (o *ExpectedSwitch) SetSlotId(v int32) {
	o.SlotId.Set(&v)
}

// SetSlotIdNil sets the value for SlotId to be an explicit nil
func (o *ExpectedSwitch) SetSlotIdNil() {
	o.SlotId.Set(nil)
}

// UnsetSlotId ensures that no value is present for SlotId, not even an explicit nil
func (o *ExpectedSwitch) UnsetSlotId() {
	o.SlotId.Unset()
}

// GetTrayIdx returns the TrayIdx field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitch) GetTrayIdx() int32 {
	if o == nil || IsNil(o.TrayIdx.Get()) {
		var ret int32
		return ret
	}
	return *o.TrayIdx.Get()
}

// GetTrayIdxOk returns a tuple with the TrayIdx field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitch) GetTrayIdxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrayIdx.Get(), o.TrayIdx.IsSet()
}

// HasTrayIdx returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasTrayIdx() bool {
	if o != nil && o.TrayIdx.IsSet() {
		return true
	}

	return false
}

// SetTrayIdx gets a reference to the given NullableInt32 and assigns it to the TrayIdx field.
func (o *ExpectedSwitch) SetTrayIdx(v int32) {
	o.TrayIdx.Set(&v)
}

// SetTrayIdxNil sets the value for TrayIdx to be an explicit nil
func (o *ExpectedSwitch) SetTrayIdxNil() {
	o.TrayIdx.Set(nil)
}

// UnsetTrayIdx ensures that no value is present for TrayIdx, not even an explicit nil
func (o *ExpectedSwitch) UnsetTrayIdx() {
	o.TrayIdx.Unset()
}

// GetHostId returns the HostId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitch) GetHostId() int32 {
	if o == nil || IsNil(o.HostId.Get()) {
		var ret int32
		return ret
	}
	return *o.HostId.Get()
}

// GetHostIdOk returns a tuple with the HostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitch) GetHostIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.HostId.Get(), o.HostId.IsSet()
}

// HasHostId returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasHostId() bool {
	if o != nil && o.HostId.IsSet() {
		return true
	}

	return false
}

// SetHostId gets a reference to the given NullableInt32 and assigns it to the HostId field.
func (o *ExpectedSwitch) SetHostId(v int32) {
	o.HostId.Set(&v)
}

// SetHostIdNil sets the value for HostId to be an explicit nil
func (o *ExpectedSwitch) SetHostIdNil() {
	o.HostId.Set(nil)
}

// UnsetHostId ensures that no value is present for HostId, not even an explicit nil
func (o *ExpectedSwitch) UnsetHostId() {
	o.HostId.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedSwitch) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ExpectedSwitch) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *ExpectedSwitch) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o ExpectedSwitch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedSwitch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.BmcMacAddress) {
		toSerialize["bmcMacAddress"] = o.BmcMacAddress
	}
	if !IsNil(o.SwitchSerialNumber) {
		toSerialize["switchSerialNumber"] = o.SwitchSerialNumber
	}
	if o.RackId.IsSet() {
		toSerialize["rackId"] = o.RackId.Get()
	}
	if o.BmcIpAddress.IsSet() {
		toSerialize["bmcIpAddress"] = o.BmcIpAddress.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Manufacturer.IsSet() {
		toSerialize["manufacturer"] = o.Manufacturer.Get()
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.SlotId.IsSet() {
		toSerialize["slotId"] = o.SlotId.Get()
	}
	if o.TrayIdx.IsSet() {
		toSerialize["trayIdx"] = o.TrayIdx.Get()
	}
	if o.HostId.IsSet() {
		toSerialize["hostId"] = o.HostId.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableExpectedSwitch struct {
	value *ExpectedSwitch
	isSet bool
}

func (v NullableExpectedSwitch) Get() *ExpectedSwitch {
	return v.value
}

func (v *NullableExpectedSwitch) Set(val *ExpectedSwitch) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedSwitch) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedSwitch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedSwitch(val *ExpectedSwitch) *NullableExpectedSwitch {
	return &NullableExpectedSwitch{value: val, isSet: true}
}

func (v NullableExpectedSwitch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedSwitch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
