// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BMCCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BMCCredentialRequest{}

// BMCCredentialRequest Request to create or update a BMC credential.
type BMCCredentialRequest struct {
	// ID of the Site where the credential is stored.
	SiteId string `json:"siteId"`
	// Which BMC credential to store.
	Kind string `json:"kind"`
	// Credential password.
	Password string `json:"password"`
	// Optional username; Core defaults to \"root\" for bmc-root when omitted.
	Username *string `json:"username,omitempty"`
	// BMC MAC address. Required for kind bmc-root, ignored for site-wide-root.
	MacAddress *string `json:"macAddress,omitempty"`
}

type _BMCCredentialRequest BMCCredentialRequest

// NewBMCCredentialRequest instantiates a new BMCCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBMCCredentialRequest(siteId string, kind string, password string) *BMCCredentialRequest {
	this := BMCCredentialRequest{}
	this.SiteId = siteId
	this.Kind = kind
	this.Password = password
	return &this
}

// NewBMCCredentialRequestWithDefaults instantiates a new BMCCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBMCCredentialRequestWithDefaults() *BMCCredentialRequest {
	this := BMCCredentialRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *BMCCredentialRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *BMCCredentialRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *BMCCredentialRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetKind returns the Kind field value
func (o *BMCCredentialRequest) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *BMCCredentialRequest) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *BMCCredentialRequest) SetKind(v string) {
	o.Kind = v
}

// GetPassword returns the Password field value
func (o *BMCCredentialRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *BMCCredentialRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *BMCCredentialRequest) SetPassword(v string) {
	o.Password = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *BMCCredentialRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BMCCredentialRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *BMCCredentialRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *BMCCredentialRequest) SetUsername(v string) {
	o.Username = &v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise.
func (o *BMCCredentialRequest) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress) {
		var ret string
		return ret
	}
	return *o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BMCCredentialRequest) GetMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MacAddress) {
		return nil, false
	}
	return o.MacAddress, true
}

// HasMacAddress returns a boolean if a field has been set.
func (o *BMCCredentialRequest) HasMacAddress() bool {
	if o != nil && !IsNil(o.MacAddress) {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given string and assigns it to the MacAddress field.
func (o *BMCCredentialRequest) SetMacAddress(v string) {
	o.MacAddress = &v
}

func (o BMCCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BMCCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["kind"] = o.Kind
	toSerialize["password"] = o.Password
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.MacAddress) {
		toSerialize["macAddress"] = o.MacAddress
	}
	return toSerialize, nil
}

func (o *BMCCredentialRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"kind",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBMCCredentialRequest := _BMCCredentialRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBMCCredentialRequest)

	if err != nil {
		return err
	}

	*o = BMCCredentialRequest(varBMCCredentialRequest)

	return err
}

type NullableBMCCredentialRequest struct {
	value *BMCCredentialRequest
	isSet bool
}

func (v NullableBMCCredentialRequest) Get() *BMCCredentialRequest {
	return v.value
}

func (v *NullableBMCCredentialRequest) Set(val *BMCCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBMCCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBMCCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBMCCredentialRequest(val *BMCCredentialRequest) *NullableBMCCredentialRequest {
	return &NullableBMCCredentialRequest{value: val, isSet: true}
}

func (v NullableBMCCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBMCCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
