// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedPowerShelfCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedPowerShelfCreateRequest{}

// ExpectedPowerShelfCreateRequest Request data to create a new Expected Power Shelf.  Note: BMC credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedPowerShelfCreateRequest struct {
	// ID of the site the Expected Power Shelf belongs to
	SiteId string `json:"siteId"`
	// MAC address of the Expected Power Shelf's BMC (Baseboard Management Controller)
	BmcMacAddress string `json:"bmcMacAddress" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Username for accessing the Expected Power Shelf's BMC
	DefaultBmcUsername NullableString `json:"defaultBmcUsername,omitempty"`
	// Password for accessing the Expected Power Shelf's BMC
	DefaultBmcPassword NullableString `json:"defaultBmcPassword,omitempty"`
	// Serial number of the Expected Power Shelf
	ShelfSerialNumber string `json:"shelfSerialNumber"`
	// Optional BMC IP address (IPv4 or IPv6). When set, pre-allocates a reserved IP for the BMC.
	BmcIpAddress NullableString `json:"bmcIpAddress,omitempty"`
	// Optional rack identifier for this component
	RackId NullableString `json:"rackId,omitempty"`
	// Display name for this component
	Name NullableString `json:"name,omitempty"`
	// Manufacturer of this component
	Manufacturer NullableString `json:"manufacturer,omitempty"`
	// Model of this component
	Model NullableString `json:"model,omitempty"`
	// Description of this component
	Description NullableString `json:"description,omitempty"`
	// Slot ID within the rack
	SlotId NullableInt32 `json:"slotId,omitempty"`
	// Tray index within the rack
	TrayIdx NullableInt32 `json:"trayIdx,omitempty"`
	// Host ID within the tray
	HostId NullableInt32 `json:"hostId,omitempty"`
	// User-defined key-value pairs for organizing and categorizing Expected Power Shelves
	Labels map[string]string `json:"labels,omitempty"`
}

type _ExpectedPowerShelfCreateRequest ExpectedPowerShelfCreateRequest

// NewExpectedPowerShelfCreateRequest instantiates a new ExpectedPowerShelfCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedPowerShelfCreateRequest(siteId string, bmcMacAddress string, shelfSerialNumber string) *ExpectedPowerShelfCreateRequest {
	this := ExpectedPowerShelfCreateRequest{}
	this.SiteId = siteId
	this.BmcMacAddress = bmcMacAddress
	this.ShelfSerialNumber = shelfSerialNumber
	return &this
}

// NewExpectedPowerShelfCreateRequestWithDefaults instantiates a new ExpectedPowerShelfCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedPowerShelfCreateRequestWithDefaults() *ExpectedPowerShelfCreateRequest {
	this := ExpectedPowerShelfCreateRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *ExpectedPowerShelfCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ExpectedPowerShelfCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetBmcMacAddress returns the BmcMacAddress field value
func (o *ExpectedPowerShelfCreateRequest) GetBmcMacAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BmcMacAddress
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfCreateRequest) GetBmcMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BmcMacAddress, true
}

// SetBmcMacAddress sets field value
func (o *ExpectedPowerShelfCreateRequest) SetBmcMacAddress(v string) {
	o.BmcMacAddress = v
}

// GetDefaultBmcUsername returns the DefaultBmcUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetDefaultBmcUsername() string {
	if o == nil || IsNil(o.DefaultBmcUsername.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcUsername.Get()
}

// GetDefaultBmcUsernameOk returns a tuple with the DefaultBmcUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetDefaultBmcUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcUsername.Get(), o.DefaultBmcUsername.IsSet()
}

// HasDefaultBmcUsername returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasDefaultBmcUsername() bool {
	if o != nil && o.DefaultBmcUsername.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcUsername gets a reference to the given NullableString and assigns it to the DefaultBmcUsername field.
func (o *ExpectedPowerShelfCreateRequest) SetDefaultBmcUsername(v string) {
	o.DefaultBmcUsername.Set(&v)
}

// SetDefaultBmcUsernameNil sets the value for DefaultBmcUsername to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetDefaultBmcUsernameNil() {
	o.DefaultBmcUsername.Set(nil)
}

// UnsetDefaultBmcUsername ensures that no value is present for DefaultBmcUsername, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetDefaultBmcUsername() {
	o.DefaultBmcUsername.Unset()
}

// GetDefaultBmcPassword returns the DefaultBmcPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetDefaultBmcPassword() string {
	if o == nil || IsNil(o.DefaultBmcPassword.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcPassword.Get()
}

// GetDefaultBmcPasswordOk returns a tuple with the DefaultBmcPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetDefaultBmcPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcPassword.Get(), o.DefaultBmcPassword.IsSet()
}

// HasDefaultBmcPassword returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasDefaultBmcPassword() bool {
	if o != nil && o.DefaultBmcPassword.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcPassword gets a reference to the given NullableString and assigns it to the DefaultBmcPassword field.
func (o *ExpectedPowerShelfCreateRequest) SetDefaultBmcPassword(v string) {
	o.DefaultBmcPassword.Set(&v)
}

// SetDefaultBmcPasswordNil sets the value for DefaultBmcPassword to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetDefaultBmcPasswordNil() {
	o.DefaultBmcPassword.Set(nil)
}

// UnsetDefaultBmcPassword ensures that no value is present for DefaultBmcPassword, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetDefaultBmcPassword() {
	o.DefaultBmcPassword.Unset()
}

// GetShelfSerialNumber returns the ShelfSerialNumber field value
func (o *ExpectedPowerShelfCreateRequest) GetShelfSerialNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShelfSerialNumber
}

// GetShelfSerialNumberOk returns a tuple with the ShelfSerialNumber field value
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfCreateRequest) GetShelfSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShelfSerialNumber, true
}

// SetShelfSerialNumber sets field value
func (o *ExpectedPowerShelfCreateRequest) SetShelfSerialNumber(v string) {
	o.ShelfSerialNumber = v
}

// GetBmcIpAddress returns the BmcIpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetBmcIpAddress() string {
	if o == nil || IsNil(o.BmcIpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.BmcIpAddress.Get()
}

// GetBmcIpAddressOk returns a tuple with the BmcIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetBmcIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcIpAddress.Get(), o.BmcIpAddress.IsSet()
}

// HasBmcIpAddress returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasBmcIpAddress() bool {
	if o != nil && o.BmcIpAddress.IsSet() {
		return true
	}

	return false
}

// SetBmcIpAddress gets a reference to the given NullableString and assigns it to the BmcIpAddress field.
func (o *ExpectedPowerShelfCreateRequest) SetBmcIpAddress(v string) {
	o.BmcIpAddress.Set(&v)
}

// SetBmcIpAddressNil sets the value for BmcIpAddress to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetBmcIpAddressNil() {
	o.BmcIpAddress.Set(nil)
}

// UnsetBmcIpAddress ensures that no value is present for BmcIpAddress, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetBmcIpAddress() {
	o.BmcIpAddress.Unset()
}

// GetRackId returns the RackId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetRackId() string {
	if o == nil || IsNil(o.RackId.Get()) {
		var ret string
		return ret
	}
	return *o.RackId.Get()
}

// GetRackIdOk returns a tuple with the RackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetRackIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RackId.Get(), o.RackId.IsSet()
}

// HasRackId returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasRackId() bool {
	if o != nil && o.RackId.IsSet() {
		return true
	}

	return false
}

// SetRackId gets a reference to the given NullableString and assigns it to the RackId field.
func (o *ExpectedPowerShelfCreateRequest) SetRackId(v string) {
	o.RackId.Set(&v)
}

// SetRackIdNil sets the value for RackId to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetRackIdNil() {
	o.RackId.Set(nil)
}

// UnsetRackId ensures that no value is present for RackId, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetRackId() {
	o.RackId.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ExpectedPowerShelfCreateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetName() {
	o.Name.Unset()
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer.Get()) {
		var ret string
		return ret
	}
	return *o.Manufacturer.Get()
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Manufacturer.Get(), o.Manufacturer.IsSet()
}

// HasManufacturer returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasManufacturer() bool {
	if o != nil && o.Manufacturer.IsSet() {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given NullableString and assigns it to the Manufacturer field.
func (o *ExpectedPowerShelfCreateRequest) SetManufacturer(v string) {
	o.Manufacturer.Set(&v)
}

// SetManufacturerNil sets the value for Manufacturer to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetManufacturerNil() {
	o.Manufacturer.Set(nil)
}

// UnsetManufacturer ensures that no value is present for Manufacturer, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetManufacturer() {
	o.Manufacturer.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *ExpectedPowerShelfCreateRequest) SetModel(v string) {
	o.Model.Set(&v)
}

// SetModelNil sets the value for Model to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetModel() {
	o.Model.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ExpectedPowerShelfCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetSlotId returns the SlotId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetSlotId() int32 {
	if o == nil || IsNil(o.SlotId.Get()) {
		var ret int32
		return ret
	}
	return *o.SlotId.Get()
}

// GetSlotIdOk returns a tuple with the SlotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetSlotIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlotId.Get(), o.SlotId.IsSet()
}

// HasSlotId returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasSlotId() bool {
	if o != nil && o.SlotId.IsSet() {
		return true
	}

	return false
}

// SetSlotId gets a reference to the given NullableInt32 and assigns it to the SlotId field.
func (o *ExpectedPowerShelfCreateRequest) SetSlotId(v int32) {
	o.SlotId.Set(&v)
}

// SetSlotIdNil sets the value for SlotId to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetSlotIdNil() {
	o.SlotId.Set(nil)
}

// UnsetSlotId ensures that no value is present for SlotId, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetSlotId() {
	o.SlotId.Unset()
}

// GetTrayIdx returns the TrayIdx field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetTrayIdx() int32 {
	if o == nil || IsNil(o.TrayIdx.Get()) {
		var ret int32
		return ret
	}
	return *o.TrayIdx.Get()
}

// GetTrayIdxOk returns a tuple with the TrayIdx field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetTrayIdxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrayIdx.Get(), o.TrayIdx.IsSet()
}

// HasTrayIdx returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasTrayIdx() bool {
	if o != nil && o.TrayIdx.IsSet() {
		return true
	}

	return false
}

// SetTrayIdx gets a reference to the given NullableInt32 and assigns it to the TrayIdx field.
func (o *ExpectedPowerShelfCreateRequest) SetTrayIdx(v int32) {
	o.TrayIdx.Set(&v)
}

// SetTrayIdxNil sets the value for TrayIdx to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetTrayIdxNil() {
	o.TrayIdx.Set(nil)
}

// UnsetTrayIdx ensures that no value is present for TrayIdx, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetTrayIdx() {
	o.TrayIdx.Unset()
}

// GetHostId returns the HostId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetHostId() int32 {
	if o == nil || IsNil(o.HostId.Get()) {
		var ret int32
		return ret
	}
	return *o.HostId.Get()
}

// GetHostIdOk returns a tuple with the HostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetHostIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.HostId.Get(), o.HostId.IsSet()
}

// HasHostId returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasHostId() bool {
	if o != nil && o.HostId.IsSet() {
		return true
	}

	return false
}

// SetHostId gets a reference to the given NullableInt32 and assigns it to the HostId field.
func (o *ExpectedPowerShelfCreateRequest) SetHostId(v int32) {
	o.HostId.Set(&v)
}

// SetHostIdNil sets the value for HostId to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetHostIdNil() {
	o.HostId.Set(nil)
}

// UnsetHostId ensures that no value is present for HostId, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetHostId() {
	o.HostId.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedPowerShelfCreateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedPowerShelfCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedPowerShelfCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedPowerShelfCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["bmcMacAddress"] = o.BmcMacAddress
	if o.DefaultBmcUsername.IsSet() {
		toSerialize["defaultBmcUsername"] = o.DefaultBmcUsername.Get()
	}
	if o.DefaultBmcPassword.IsSet() {
		toSerialize["defaultBmcPassword"] = o.DefaultBmcPassword.Get()
	}
	toSerialize["shelfSerialNumber"] = o.ShelfSerialNumber
	if o.BmcIpAddress.IsSet() {
		toSerialize["bmcIpAddress"] = o.BmcIpAddress.Get()
	}
	if o.RackId.IsSet() {
		toSerialize["rackId"] = o.RackId.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Manufacturer.IsSet() {
		toSerialize["manufacturer"] = o.Manufacturer.Get()
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.SlotId.IsSet() {
		toSerialize["slotId"] = o.SlotId.Get()
	}
	if o.TrayIdx.IsSet() {
		toSerialize["trayIdx"] = o.TrayIdx.Get()
	}
	if o.HostId.IsSet() {
		toSerialize["hostId"] = o.HostId.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *ExpectedPowerShelfCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"bmcMacAddress",
		"shelfSerialNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedPowerShelfCreateRequest := _ExpectedPowerShelfCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExpectedPowerShelfCreateRequest)

	if err != nil {
		return err
	}

	*o = ExpectedPowerShelfCreateRequest(varExpectedPowerShelfCreateRequest)

	return err
}

type NullableExpectedPowerShelfCreateRequest struct {
	value *ExpectedPowerShelfCreateRequest
	isSet bool
}

func (v NullableExpectedPowerShelfCreateRequest) Get() *ExpectedPowerShelfCreateRequest {
	return v.value
}

func (v *NullableExpectedPowerShelfCreateRequest) Set(val *ExpectedPowerShelfCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedPowerShelfCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedPowerShelfCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedPowerShelfCreateRequest(val *ExpectedPowerShelfCreateRequest) *NullableExpectedPowerShelfCreateRequest {
	return &NullableExpectedPowerShelfCreateRequest{value: val, isSet: true}
}

func (v NullableExpectedPowerShelfCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedPowerShelfCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
