// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchRackFirmwareUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchRackFirmwareUpdateRequest{}

// BatchRackFirmwareUpdateRequest Request body for batch rack firmware update operations
type BatchRackFirmwareUpdateRequest struct {
	// ID of the Site
	SiteId string `json:"siteId"`
	// Filter that selects Racks targeted for firmware update
	Filter *RackFilter `json:"filter,omitempty"`
	// Target firmware version.
	Version NullableString `json:"version,omitempty"`
	// Optional Operation Rule UUID. When set, pins every task spawned by this batch to the named rule and overrides Flow's default rule resolution.
	RuleId *string `json:"ruleId,omitempty"`
	// When true, proceed even if one or more target components (or hosts on the owning rack for rack-scoped components) are reported as not ready by their persisted status. Intended for operator-supervised maintenance.
	OverrideReadinessCheck *bool `json:"overrideReadinessCheck,omitempty"`
}

type _BatchRackFirmwareUpdateRequest BatchRackFirmwareUpdateRequest

// NewBatchRackFirmwareUpdateRequest instantiates a new BatchRackFirmwareUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchRackFirmwareUpdateRequest(siteId string) *BatchRackFirmwareUpdateRequest {
	this := BatchRackFirmwareUpdateRequest{}
	this.SiteId = siteId
	var overrideReadinessCheck bool = false
	this.OverrideReadinessCheck = &overrideReadinessCheck
	return &this
}

// NewBatchRackFirmwareUpdateRequestWithDefaults instantiates a new BatchRackFirmwareUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchRackFirmwareUpdateRequestWithDefaults() *BatchRackFirmwareUpdateRequest {
	this := BatchRackFirmwareUpdateRequest{}
	var overrideReadinessCheck bool = false
	this.OverrideReadinessCheck = &overrideReadinessCheck
	return &this
}

// GetSiteId returns the SiteId field value
func (o *BatchRackFirmwareUpdateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *BatchRackFirmwareUpdateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *BatchRackFirmwareUpdateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *BatchRackFirmwareUpdateRequest) GetFilter() RackFilter {
	if o == nil || IsNil(o.Filter) {
		var ret RackFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchRackFirmwareUpdateRequest) GetFilterOk() (*RackFilter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *BatchRackFirmwareUpdateRequest) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given RackFilter and assigns it to the Filter field.
func (o *BatchRackFirmwareUpdateRequest) SetFilter(v RackFilter) {
	o.Filter = &v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchRackFirmwareUpdateRequest) GetVersion() string {
	if o == nil || IsNil(o.Version.Get()) {
		var ret string
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchRackFirmwareUpdateRequest) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *BatchRackFirmwareUpdateRequest) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableString and assigns it to the Version field.
func (o *BatchRackFirmwareUpdateRequest) SetVersion(v string) {
	o.Version.Set(&v)
}

// SetVersionNil sets the value for Version to be an explicit nil
func (o *BatchRackFirmwareUpdateRequest) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *BatchRackFirmwareUpdateRequest) UnsetVersion() {
	o.Version.Unset()
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *BatchRackFirmwareUpdateRequest) GetRuleId() string {
	if o == nil || IsNil(o.RuleId) {
		var ret string
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchRackFirmwareUpdateRequest) GetRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RuleId) {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *BatchRackFirmwareUpdateRequest) HasRuleId() bool {
	if o != nil && !IsNil(o.RuleId) {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given string and assigns it to the RuleId field.
func (o *BatchRackFirmwareUpdateRequest) SetRuleId(v string) {
	o.RuleId = &v
}

// GetOverrideReadinessCheck returns the OverrideReadinessCheck field value if set, zero value otherwise.
func (o *BatchRackFirmwareUpdateRequest) GetOverrideReadinessCheck() bool {
	if o == nil || IsNil(o.OverrideReadinessCheck) {
		var ret bool
		return ret
	}
	return *o.OverrideReadinessCheck
}

// GetOverrideReadinessCheckOk returns a tuple with the OverrideReadinessCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchRackFirmwareUpdateRequest) GetOverrideReadinessCheckOk() (*bool, bool) {
	if o == nil || IsNil(o.OverrideReadinessCheck) {
		return nil, false
	}
	return o.OverrideReadinessCheck, true
}

// HasOverrideReadinessCheck returns a boolean if a field has been set.
func (o *BatchRackFirmwareUpdateRequest) HasOverrideReadinessCheck() bool {
	if o != nil && !IsNil(o.OverrideReadinessCheck) {
		return true
	}

	return false
}

// SetOverrideReadinessCheck gets a reference to the given bool and assigns it to the OverrideReadinessCheck field.
func (o *BatchRackFirmwareUpdateRequest) SetOverrideReadinessCheck(v bool) {
	o.OverrideReadinessCheck = &v
}

func (o BatchRackFirmwareUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchRackFirmwareUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	if !IsNil(o.RuleId) {
		toSerialize["ruleId"] = o.RuleId
	}
	if !IsNil(o.OverrideReadinessCheck) {
		toSerialize["overrideReadinessCheck"] = o.OverrideReadinessCheck
	}
	return toSerialize, nil
}

func (o *BatchRackFirmwareUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchRackFirmwareUpdateRequest := _BatchRackFirmwareUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchRackFirmwareUpdateRequest)

	if err != nil {
		return err
	}

	*o = BatchRackFirmwareUpdateRequest(varBatchRackFirmwareUpdateRequest)

	return err
}

type NullableBatchRackFirmwareUpdateRequest struct {
	value *BatchRackFirmwareUpdateRequest
	isSet bool
}

func (v NullableBatchRackFirmwareUpdateRequest) Get() *BatchRackFirmwareUpdateRequest {
	return v.value
}

func (v *NullableBatchRackFirmwareUpdateRequest) Set(val *BatchRackFirmwareUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchRackFirmwareUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchRackFirmwareUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchRackFirmwareUpdateRequest(val *BatchRackFirmwareUpdateRequest) *NullableBatchRackFirmwareUpdateRequest {
	return &NullableBatchRackFirmwareUpdateRequest{value: val, isSet: true}
}

func (v NullableBatchRackFirmwareUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchRackFirmwareUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
