// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the Interface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Interface{}

// Interface Associates an Instance with a Subnet
type Interface struct {
	// Unique UUID v4 identifier for the Interface
	Id *string `json:"id,omitempty"`
	// ID of the associated Instance
	InstanceId *string `json:"instanceId,omitempty"`
	// ID of the associated Subnet
	SubnetId NullableString `json:"subnetId,omitempty"`
	// ID of the associated VPCPrefix
	VpcPrefixId NullableString `json:"vpcPrefixId,omitempty"`
	// IsPhysical indicates whether the Subnet is bound on a physical Interface
	IsPhysical *bool `json:"isPhysical,omitempty"`
	// Name of the device to use
	Device NullableString `json:"device,omitempty"`
	// Index of the device, used to identify which interface card to attache the Partition to
	DeviceInstance NullableInt32 `json:"deviceInstance,omitempty"`
	// Must be specified if isPhysical is false
	VirtualFunctionId NullableInt32 `json:"virtualFunctionId,omitempty"`
	// MAC address of the Interface
	MacAddress NullableString `json:"macAddress,omitempty"`
	// A list of IPv4 or IPv6 addresses
	IpAddresses []string `json:"ipAddresses,omitempty"`
	// Explicitly requested IP address for the interface. This is only used for VPC Prefix-based interfaces and is not valid for Subnet-based interfaces. The least-significant host bit must be 1.
	RequestedIpAddress NullableString `json:"requestedIpAddress,omitempty"`
	// Inline interface-local routing profile options. Only valid for VPC Prefix-based interfaces.
	InlineRoutingProfile NullableInterfaceInlineRoutingProfile `json:"inlineRoutingProfile,omitempty"`
	// Status of the Interface
	Status *InterfaceStatus `json:"status,omitempty"`
	// Date/time when the Interface was created
	Created *time.Time `json:"created,omitempty"`
	// Date/time when the Interface was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewInterface instantiates a new Interface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterface() *Interface {
	this := Interface{}
	return &this
}

// NewInterfaceWithDefaults instantiates a new Interface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfaceWithDefaults() *Interface {
	this := Interface{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Interface) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interface) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Interface) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Interface) SetId(v string) {
	o.Id = &v
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *Interface) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interface) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *Interface) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *Interface) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetSubnetId returns the SubnetId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Interface) GetSubnetId() string {
	if o == nil || IsNil(o.SubnetId.Get()) {
		var ret string
		return ret
	}
	return *o.SubnetId.Get()
}

// GetSubnetIdOk returns a tuple with the SubnetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Interface) GetSubnetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubnetId.Get(), o.SubnetId.IsSet()
}

// HasSubnetId returns a boolean if a field has been set.
func (o *Interface) HasSubnetId() bool {
	if o != nil && o.SubnetId.IsSet() {
		return true
	}

	return false
}

// SetSubnetId gets a reference to the given NullableString and assigns it to the SubnetId field.
func (o *Interface) SetSubnetId(v string) {
	o.SubnetId.Set(&v)
}

// SetSubnetIdNil sets the value for SubnetId to be an explicit nil
func (o *Interface) SetSubnetIdNil() {
	o.SubnetId.Set(nil)
}

// UnsetSubnetId ensures that no value is present for SubnetId, not even an explicit nil
func (o *Interface) UnsetSubnetId() {
	o.SubnetId.Unset()
}

// GetVpcPrefixId returns the VpcPrefixId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Interface) GetVpcPrefixId() string {
	if o == nil || IsNil(o.VpcPrefixId.Get()) {
		var ret string
		return ret
	}
	return *o.VpcPrefixId.Get()
}

// GetVpcPrefixIdOk returns a tuple with the VpcPrefixId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Interface) GetVpcPrefixIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VpcPrefixId.Get(), o.VpcPrefixId.IsSet()
}

// HasVpcPrefixId returns a boolean if a field has been set.
func (o *Interface) HasVpcPrefixId() bool {
	if o != nil && o.VpcPrefixId.IsSet() {
		return true
	}

	return false
}

// SetVpcPrefixId gets a reference to the given NullableString and assigns it to the VpcPrefixId field.
func (o *Interface) SetVpcPrefixId(v string) {
	o.VpcPrefixId.Set(&v)
}

// SetVpcPrefixIdNil sets the value for VpcPrefixId to be an explicit nil
func (o *Interface) SetVpcPrefixIdNil() {
	o.VpcPrefixId.Set(nil)
}

// UnsetVpcPrefixId ensures that no value is present for VpcPrefixId, not even an explicit nil
func (o *Interface) UnsetVpcPrefixId() {
	o.VpcPrefixId.Unset()
}

// GetIsPhysical returns the IsPhysical field value if set, zero value otherwise.
func (o *Interface) GetIsPhysical() bool {
	if o == nil || IsNil(o.IsPhysical) {
		var ret bool
		return ret
	}
	return *o.IsPhysical
}

// GetIsPhysicalOk returns a tuple with the IsPhysical field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interface) GetIsPhysicalOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPhysical) {
		return nil, false
	}
	return o.IsPhysical, true
}

// HasIsPhysical returns a boolean if a field has been set.
func (o *Interface) HasIsPhysical() bool {
	if o != nil && !IsNil(o.IsPhysical) {
		return true
	}

	return false
}

// SetIsPhysical gets a reference to the given bool and assigns it to the IsPhysical field.
func (o *Interface) SetIsPhysical(v bool) {
	o.IsPhysical = &v
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Interface) GetDevice() string {
	if o == nil || IsNil(o.Device.Get()) {
		var ret string
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Interface) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *Interface) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableString and assigns it to the Device field.
func (o *Interface) SetDevice(v string) {
	o.Device.Set(&v)
}

// SetDeviceNil sets the value for Device to be an explicit nil
func (o *Interface) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *Interface) UnsetDevice() {
	o.Device.Unset()
}

// GetDeviceInstance returns the DeviceInstance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Interface) GetDeviceInstance() int32 {
	if o == nil || IsNil(o.DeviceInstance.Get()) {
		var ret int32
		return ret
	}
	return *o.DeviceInstance.Get()
}

// GetDeviceInstanceOk returns a tuple with the DeviceInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Interface) GetDeviceInstanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceInstance.Get(), o.DeviceInstance.IsSet()
}

// HasDeviceInstance returns a boolean if a field has been set.
func (o *Interface) HasDeviceInstance() bool {
	if o != nil && o.DeviceInstance.IsSet() {
		return true
	}

	return false
}

// SetDeviceInstance gets a reference to the given NullableInt32 and assigns it to the DeviceInstance field.
func (o *Interface) SetDeviceInstance(v int32) {
	o.DeviceInstance.Set(&v)
}

// SetDeviceInstanceNil sets the value for DeviceInstance to be an explicit nil
func (o *Interface) SetDeviceInstanceNil() {
	o.DeviceInstance.Set(nil)
}

// UnsetDeviceInstance ensures that no value is present for DeviceInstance, not even an explicit nil
func (o *Interface) UnsetDeviceInstance() {
	o.DeviceInstance.Unset()
}

// GetVirtualFunctionId returns the VirtualFunctionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Interface) GetVirtualFunctionId() int32 {
	if o == nil || IsNil(o.VirtualFunctionId.Get()) {
		var ret int32
		return ret
	}
	return *o.VirtualFunctionId.Get()
}

// GetVirtualFunctionIdOk returns a tuple with the VirtualFunctionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Interface) GetVirtualFunctionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VirtualFunctionId.Get(), o.VirtualFunctionId.IsSet()
}

// HasVirtualFunctionId returns a boolean if a field has been set.
func (o *Interface) HasVirtualFunctionId() bool {
	if o != nil && o.VirtualFunctionId.IsSet() {
		return true
	}

	return false
}

// SetVirtualFunctionId gets a reference to the given NullableInt32 and assigns it to the VirtualFunctionId field.
func (o *Interface) SetVirtualFunctionId(v int32) {
	o.VirtualFunctionId.Set(&v)
}

// SetVirtualFunctionIdNil sets the value for VirtualFunctionId to be an explicit nil
func (o *Interface) SetVirtualFunctionIdNil() {
	o.VirtualFunctionId.Set(nil)
}

// UnsetVirtualFunctionId ensures that no value is present for VirtualFunctionId, not even an explicit nil
func (o *Interface) UnsetVirtualFunctionId() {
	o.VirtualFunctionId.Unset()
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Interface) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.MacAddress.Get()
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Interface) GetMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MacAddress.Get(), o.MacAddress.IsSet()
}

// HasMacAddress returns a boolean if a field has been set.
func (o *Interface) HasMacAddress() bool {
	if o != nil && o.MacAddress.IsSet() {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given NullableString and assigns it to the MacAddress field.
func (o *Interface) SetMacAddress(v string) {
	o.MacAddress.Set(&v)
}

// SetMacAddressNil sets the value for MacAddress to be an explicit nil
func (o *Interface) SetMacAddressNil() {
	o.MacAddress.Set(nil)
}

// UnsetMacAddress ensures that no value is present for MacAddress, not even an explicit nil
func (o *Interface) UnsetMacAddress() {
	o.MacAddress.Unset()
}

// GetIpAddresses returns the IpAddresses field value if set, zero value otherwise.
func (o *Interface) GetIpAddresses() []string {
	if o == nil || IsNil(o.IpAddresses) {
		var ret []string
		return ret
	}
	return o.IpAddresses
}

// GetIpAddressesOk returns a tuple with the IpAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interface) GetIpAddressesOk() ([]string, bool) {
	if o == nil || IsNil(o.IpAddresses) {
		return nil, false
	}
	return o.IpAddresses, true
}

// HasIpAddresses returns a boolean if a field has been set.
func (o *Interface) HasIpAddresses() bool {
	if o != nil && !IsNil(o.IpAddresses) {
		return true
	}

	return false
}

// SetIpAddresses gets a reference to the given []string and assigns it to the IpAddresses field.
func (o *Interface) SetIpAddresses(v []string) {
	o.IpAddresses = v
}

// GetRequestedIpAddress returns the RequestedIpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Interface) GetRequestedIpAddress() string {
	if o == nil || IsNil(o.RequestedIpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.RequestedIpAddress.Get()
}

// GetRequestedIpAddressOk returns a tuple with the RequestedIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Interface) GetRequestedIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestedIpAddress.Get(), o.RequestedIpAddress.IsSet()
}

// HasRequestedIpAddress returns a boolean if a field has been set.
func (o *Interface) HasRequestedIpAddress() bool {
	if o != nil && o.RequestedIpAddress.IsSet() {
		return true
	}

	return false
}

// SetRequestedIpAddress gets a reference to the given NullableString and assigns it to the RequestedIpAddress field.
func (o *Interface) SetRequestedIpAddress(v string) {
	o.RequestedIpAddress.Set(&v)
}

// SetRequestedIpAddressNil sets the value for RequestedIpAddress to be an explicit nil
func (o *Interface) SetRequestedIpAddressNil() {
	o.RequestedIpAddress.Set(nil)
}

// UnsetRequestedIpAddress ensures that no value is present for RequestedIpAddress, not even an explicit nil
func (o *Interface) UnsetRequestedIpAddress() {
	o.RequestedIpAddress.Unset()
}

// GetInlineRoutingProfile returns the InlineRoutingProfile field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Interface) GetInlineRoutingProfile() InterfaceInlineRoutingProfile {
	if o == nil || IsNil(o.InlineRoutingProfile.Get()) {
		var ret InterfaceInlineRoutingProfile
		return ret
	}
	return *o.InlineRoutingProfile.Get()
}

// GetInlineRoutingProfileOk returns a tuple with the InlineRoutingProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Interface) GetInlineRoutingProfileOk() (*InterfaceInlineRoutingProfile, bool) {
	if o == nil {
		return nil, false
	}
	return o.InlineRoutingProfile.Get(), o.InlineRoutingProfile.IsSet()
}

// HasInlineRoutingProfile returns a boolean if a field has been set.
func (o *Interface) HasInlineRoutingProfile() bool {
	if o != nil && o.InlineRoutingProfile.IsSet() {
		return true
	}

	return false
}

// SetInlineRoutingProfile gets a reference to the given NullableInterfaceInlineRoutingProfile and assigns it to the InlineRoutingProfile field.
func (o *Interface) SetInlineRoutingProfile(v InterfaceInlineRoutingProfile) {
	o.InlineRoutingProfile.Set(&v)
}

// SetInlineRoutingProfileNil sets the value for InlineRoutingProfile to be an explicit nil
func (o *Interface) SetInlineRoutingProfileNil() {
	o.InlineRoutingProfile.Set(nil)
}

// UnsetInlineRoutingProfile ensures that no value is present for InlineRoutingProfile, not even an explicit nil
func (o *Interface) UnsetInlineRoutingProfile() {
	o.InlineRoutingProfile.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Interface) GetStatus() InterfaceStatus {
	if o == nil || IsNil(o.Status) {
		var ret InterfaceStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interface) GetStatusOk() (*InterfaceStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Interface) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given InterfaceStatus and assigns it to the Status field.
func (o *Interface) SetStatus(v InterfaceStatus) {
	o.Status = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Interface) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interface) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Interface) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *Interface) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *Interface) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Interface) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *Interface) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *Interface) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o Interface) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Interface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InstanceId) {
		toSerialize["instanceId"] = o.InstanceId
	}
	if o.SubnetId.IsSet() {
		toSerialize["subnetId"] = o.SubnetId.Get()
	}
	if o.VpcPrefixId.IsSet() {
		toSerialize["vpcPrefixId"] = o.VpcPrefixId.Get()
	}
	if !IsNil(o.IsPhysical) {
		toSerialize["isPhysical"] = o.IsPhysical
	}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	if o.DeviceInstance.IsSet() {
		toSerialize["deviceInstance"] = o.DeviceInstance.Get()
	}
	if o.VirtualFunctionId.IsSet() {
		toSerialize["virtualFunctionId"] = o.VirtualFunctionId.Get()
	}
	if o.MacAddress.IsSet() {
		toSerialize["macAddress"] = o.MacAddress.Get()
	}
	if !IsNil(o.IpAddresses) {
		toSerialize["ipAddresses"] = o.IpAddresses
	}
	if o.RequestedIpAddress.IsSet() {
		toSerialize["requestedIpAddress"] = o.RequestedIpAddress.Get()
	}
	if o.InlineRoutingProfile.IsSet() {
		toSerialize["inlineRoutingProfile"] = o.InlineRoutingProfile.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableInterface struct {
	value *Interface
	isSet bool
}

func (v NullableInterface) Get() *Interface {
	return v.value
}

func (v *NullableInterface) Set(val *Interface) {
	v.value = val
	v.isSet = true
}

func (v NullableInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterface(val *Interface) *NullableInterface {
	return &NullableInterface{value: val, isSet: true}
}

func (v NullableInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
