// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// TenantIdentityConfigCreateOrUpdateRequest - Tenant identity configuration payload. `issuer`, `defaultAudience`, and `tokenTtlSeconds` are required. `enabled` is optional and defaults to `true` when omitted. The `org` identifier is taken from the URL path segment `{org}`.  Two request shapes are supported, distinguished by whether the PUT also forces a signing-key rotation:    1. **Without key rotation** -- `rotateKey` is omitted or `false`;      `signingKeyOverlapSeconds` must be omitted.   2. **With key rotation** -- `rotateKey: true` and      `signingKeyOverlapSeconds` are both required; the Core gRPC      API generates a fresh ES256 keypair into the other key slot,      swaps the active signer, and arms a JWKS overlap window for      the previous key.
type TenantIdentityConfigCreateOrUpdateRequest struct {
	TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation    *TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation
	TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation *TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation
}

// TenantIdentityConfigCreateOrUpdateRequestWithKeyRotationAsTenantIdentityConfigCreateOrUpdateRequest is a convenience function that returns TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation wrapped in TenantIdentityConfigCreateOrUpdateRequest
func TenantIdentityConfigCreateOrUpdateRequestWithKeyRotationAsTenantIdentityConfigCreateOrUpdateRequest(v *TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation) TenantIdentityConfigCreateOrUpdateRequest {
	return TenantIdentityConfigCreateOrUpdateRequest{
		TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation: v,
	}
}

// TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotationAsTenantIdentityConfigCreateOrUpdateRequest is a convenience function that returns TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation wrapped in TenantIdentityConfigCreateOrUpdateRequest
func TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotationAsTenantIdentityConfigCreateOrUpdateRequest(v *TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation) TenantIdentityConfigCreateOrUpdateRequest {
	return TenantIdentityConfigCreateOrUpdateRequest{
		TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *TenantIdentityConfigCreateOrUpdateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation
	err = newStrictDecoder(data).Decode(&dst.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation)
	if err == nil {
		jsonTenantIdentityConfigCreateOrUpdateRequestWithKeyRotation, _ := json.Marshal(dst.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation)
		if string(jsonTenantIdentityConfigCreateOrUpdateRequestWithKeyRotation) == "{}" { // empty struct
			dst.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation = nil
		} else {
			if err = validator.Validate(dst.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation); err != nil {
				dst.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation = nil
			} else {
				match++
			}
		}
	} else {
		dst.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation = nil
	}

	// try to unmarshal data into TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation
	err = newStrictDecoder(data).Decode(&dst.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation)
	if err == nil {
		jsonTenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation, _ := json.Marshal(dst.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation)
		if string(jsonTenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation) == "{}" { // empty struct
			dst.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation = nil
		} else {
			if err = validator.Validate(dst.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation); err != nil {
				dst.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation = nil
			} else {
				match++
			}
		}
	} else {
		dst.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation = nil
		dst.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TenantIdentityConfigCreateOrUpdateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TenantIdentityConfigCreateOrUpdateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TenantIdentityConfigCreateOrUpdateRequest) MarshalJSON() ([]byte, error) {
	if src.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation != nil {
		return json.Marshal(&src.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation)
	}

	if src.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation != nil {
		return json.Marshal(&src.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TenantIdentityConfigCreateOrUpdateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation != nil {
		return obj.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation
	}

	if obj.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation != nil {
		return obj.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TenantIdentityConfigCreateOrUpdateRequest) GetActualInstanceValue() interface{} {
	if obj.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation != nil {
		return *obj.TenantIdentityConfigCreateOrUpdateRequestWithKeyRotation
	}

	if obj.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation != nil {
		return *obj.TenantIdentityConfigCreateOrUpdateRequestWithoutKeyRotation
	}

	// all schemas are nil
	return nil
}

type NullableTenantIdentityConfigCreateOrUpdateRequest struct {
	value *TenantIdentityConfigCreateOrUpdateRequest
	isSet bool
}

func (v NullableTenantIdentityConfigCreateOrUpdateRequest) Get() *TenantIdentityConfigCreateOrUpdateRequest {
	return v.value
}

func (v *NullableTenantIdentityConfigCreateOrUpdateRequest) Set(val *TenantIdentityConfigCreateOrUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantIdentityConfigCreateOrUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantIdentityConfigCreateOrUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantIdentityConfigCreateOrUpdateRequest(val *TenantIdentityConfigCreateOrUpdateRequest) *NullableTenantIdentityConfigCreateOrUpdateRequest {
	return &NullableTenantIdentityConfigCreateOrUpdateRequest{value: val, isSet: true}
}

func (v NullableTenantIdentityConfigCreateOrUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantIdentityConfigCreateOrUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
