// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the ExpectedMachine type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedMachine{}

// ExpectedMachine An Expected Machine represents a physical machine that is expected to be discovered at a site, with hardware identifiers and metadata.  Note: BMC credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedMachine struct {
	// Unique identifier for the Expected Machine
	Id *string `json:"id,omitempty"`
	// ID of the site the Expected Machine belongs to
	SiteId *string `json:"siteId,omitempty"`
	// MAC address of the Expected Machine's BMC (Baseboard Management Controller)
	BmcMacAddress *string `json:"bmcMacAddress,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Serial number of the Expected Machine's chassis
	ChassisSerialNumber *string `json:"chassisSerialNumber,omitempty"`
	// Serial numbers of the Expected Machine's fallback DPUs (Data Processing Units)
	FallbackDPUSerialNumbers []string `json:"fallbackDPUSerialNumbers,omitempty"`
	// Optional ID of the SKU associated with this Expected Machine
	SkuId NullableString `json:"skuId,omitempty"`
	// SKU information for this Expected Machine (populated when includeRelation=Sku is specified)
	Sku *Sku `json:"sku,omitempty"`
	// Optional ID of the Machine associated with this Expected Machine
	MachineId NullableString `json:"machineId,omitempty"`
	// Machine information for this Expected Machine (populated when includeRelation=Machine is specified)
	Machine *MachineSummary `json:"machine,omitempty"`
	// Optional rack identifier for this component
	RackId NullableString `json:"rackId,omitempty"`
	// Optional BMC IP address (IPv4 or IPv6). When set, pre-allocates a reserved IP for the BMC.
	BmcIpAddress NullableString `json:"bmcIpAddress,omitempty"`
	// Display name for this component
	Name NullableString `json:"name,omitempty"`
	// Manufacturer of this component
	Manufacturer NullableString `json:"manufacturer,omitempty"`
	// Model of this component
	Model NullableString `json:"model,omitempty"`
	// Description of this component
	Description NullableString `json:"description,omitempty"`
	// Slot ID within the rack
	SlotId NullableInt32 `json:"slotId,omitempty"`
	// Tray index within the rack
	TrayIdx NullableInt32 `json:"trayIdx,omitempty"`
	// Host ID within the tray
	HostId NullableInt32 `json:"hostId,omitempty"`
	// User-defined key-value pairs for organizing and categorizing Expected Machines
	Labels map[string]string `json:"labels,omitempty"`
	// ISO 8601 datetime when the Expected Machine was created
	Created *time.Time `json:"created,omitempty"`
	// ISO 8601 datetime when the Expected Machine was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewExpectedMachine instantiates a new ExpectedMachine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedMachine() *ExpectedMachine {
	this := ExpectedMachine{}
	return &this
}

// NewExpectedMachineWithDefaults instantiates a new ExpectedMachine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedMachineWithDefaults() *ExpectedMachine {
	this := ExpectedMachine{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ExpectedMachine) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ExpectedMachine) SetId(v string) {
	o.Id = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *ExpectedMachine) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *ExpectedMachine) SetSiteId(v string) {
	o.SiteId = &v
}

// GetBmcMacAddress returns the BmcMacAddress field value if set, zero value otherwise.
func (o *ExpectedMachine) GetBmcMacAddress() string {
	if o == nil || IsNil(o.BmcMacAddress) {
		var ret string
		return ret
	}
	return *o.BmcMacAddress
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetBmcMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.BmcMacAddress) {
		return nil, false
	}
	return o.BmcMacAddress, true
}

// HasBmcMacAddress returns a boolean if a field has been set.
func (o *ExpectedMachine) HasBmcMacAddress() bool {
	if o != nil && !IsNil(o.BmcMacAddress) {
		return true
	}

	return false
}

// SetBmcMacAddress gets a reference to the given string and assigns it to the BmcMacAddress field.
func (o *ExpectedMachine) SetBmcMacAddress(v string) {
	o.BmcMacAddress = &v
}

// GetChassisSerialNumber returns the ChassisSerialNumber field value if set, zero value otherwise.
func (o *ExpectedMachine) GetChassisSerialNumber() string {
	if o == nil || IsNil(o.ChassisSerialNumber) {
		var ret string
		return ret
	}
	return *o.ChassisSerialNumber
}

// GetChassisSerialNumberOk returns a tuple with the ChassisSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetChassisSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ChassisSerialNumber) {
		return nil, false
	}
	return o.ChassisSerialNumber, true
}

// HasChassisSerialNumber returns a boolean if a field has been set.
func (o *ExpectedMachine) HasChassisSerialNumber() bool {
	if o != nil && !IsNil(o.ChassisSerialNumber) {
		return true
	}

	return false
}

// SetChassisSerialNumber gets a reference to the given string and assigns it to the ChassisSerialNumber field.
func (o *ExpectedMachine) SetChassisSerialNumber(v string) {
	o.ChassisSerialNumber = &v
}

// GetFallbackDPUSerialNumbers returns the FallbackDPUSerialNumbers field value if set, zero value otherwise.
func (o *ExpectedMachine) GetFallbackDPUSerialNumbers() []string {
	if o == nil || IsNil(o.FallbackDPUSerialNumbers) {
		var ret []string
		return ret
	}
	return o.FallbackDPUSerialNumbers
}

// GetFallbackDPUSerialNumbersOk returns a tuple with the FallbackDPUSerialNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetFallbackDPUSerialNumbersOk() ([]string, bool) {
	if o == nil || IsNil(o.FallbackDPUSerialNumbers) {
		return nil, false
	}
	return o.FallbackDPUSerialNumbers, true
}

// HasFallbackDPUSerialNumbers returns a boolean if a field has been set.
func (o *ExpectedMachine) HasFallbackDPUSerialNumbers() bool {
	if o != nil && !IsNil(o.FallbackDPUSerialNumbers) {
		return true
	}

	return false
}

// SetFallbackDPUSerialNumbers gets a reference to the given []string and assigns it to the FallbackDPUSerialNumbers field.
func (o *ExpectedMachine) SetFallbackDPUSerialNumbers(v []string) {
	o.FallbackDPUSerialNumbers = v
}

// GetSkuId returns the SkuId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetSkuId() string {
	if o == nil || IsNil(o.SkuId.Get()) {
		var ret string
		return ret
	}
	return *o.SkuId.Get()
}

// GetSkuIdOk returns a tuple with the SkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetSkuIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SkuId.Get(), o.SkuId.IsSet()
}

// HasSkuId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasSkuId() bool {
	if o != nil && o.SkuId.IsSet() {
		return true
	}

	return false
}

// SetSkuId gets a reference to the given NullableString and assigns it to the SkuId field.
func (o *ExpectedMachine) SetSkuId(v string) {
	o.SkuId.Set(&v)
}

// SetSkuIdNil sets the value for SkuId to be an explicit nil
func (o *ExpectedMachine) SetSkuIdNil() {
	o.SkuId.Set(nil)
}

// UnsetSkuId ensures that no value is present for SkuId, not even an explicit nil
func (o *ExpectedMachine) UnsetSkuId() {
	o.SkuId.Unset()
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *ExpectedMachine) GetSku() Sku {
	if o == nil || IsNil(o.Sku) {
		var ret Sku
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetSkuOk() (*Sku, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *ExpectedMachine) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given Sku and assigns it to the Sku field.
func (o *ExpectedMachine) SetSku(v Sku) {
	o.Sku = &v
}

// GetMachineId returns the MachineId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetMachineId() string {
	if o == nil || IsNil(o.MachineId.Get()) {
		var ret string
		return ret
	}
	return *o.MachineId.Get()
}

// GetMachineIdOk returns a tuple with the MachineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MachineId.Get(), o.MachineId.IsSet()
}

// HasMachineId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasMachineId() bool {
	if o != nil && o.MachineId.IsSet() {
		return true
	}

	return false
}

// SetMachineId gets a reference to the given NullableString and assigns it to the MachineId field.
func (o *ExpectedMachine) SetMachineId(v string) {
	o.MachineId.Set(&v)
}

// SetMachineIdNil sets the value for MachineId to be an explicit nil
func (o *ExpectedMachine) SetMachineIdNil() {
	o.MachineId.Set(nil)
}

// UnsetMachineId ensures that no value is present for MachineId, not even an explicit nil
func (o *ExpectedMachine) UnsetMachineId() {
	o.MachineId.Unset()
}

// GetMachine returns the Machine field value if set, zero value otherwise.
func (o *ExpectedMachine) GetMachine() MachineSummary {
	if o == nil || IsNil(o.Machine) {
		var ret MachineSummary
		return ret
	}
	return *o.Machine
}

// GetMachineOk returns a tuple with the Machine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetMachineOk() (*MachineSummary, bool) {
	if o == nil || IsNil(o.Machine) {
		return nil, false
	}
	return o.Machine, true
}

// HasMachine returns a boolean if a field has been set.
func (o *ExpectedMachine) HasMachine() bool {
	if o != nil && !IsNil(o.Machine) {
		return true
	}

	return false
}

// SetMachine gets a reference to the given MachineSummary and assigns it to the Machine field.
func (o *ExpectedMachine) SetMachine(v MachineSummary) {
	o.Machine = &v
}

// GetRackId returns the RackId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetRackId() string {
	if o == nil || IsNil(o.RackId.Get()) {
		var ret string
		return ret
	}
	return *o.RackId.Get()
}

// GetRackIdOk returns a tuple with the RackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetRackIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RackId.Get(), o.RackId.IsSet()
}

// HasRackId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasRackId() bool {
	if o != nil && o.RackId.IsSet() {
		return true
	}

	return false
}

// SetRackId gets a reference to the given NullableString and assigns it to the RackId field.
func (o *ExpectedMachine) SetRackId(v string) {
	o.RackId.Set(&v)
}

// SetRackIdNil sets the value for RackId to be an explicit nil
func (o *ExpectedMachine) SetRackIdNil() {
	o.RackId.Set(nil)
}

// UnsetRackId ensures that no value is present for RackId, not even an explicit nil
func (o *ExpectedMachine) UnsetRackId() {
	o.RackId.Unset()
}

// GetBmcIpAddress returns the BmcIpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetBmcIpAddress() string {
	if o == nil || IsNil(o.BmcIpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.BmcIpAddress.Get()
}

// GetBmcIpAddressOk returns a tuple with the BmcIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetBmcIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcIpAddress.Get(), o.BmcIpAddress.IsSet()
}

// HasBmcIpAddress returns a boolean if a field has been set.
func (o *ExpectedMachine) HasBmcIpAddress() bool {
	if o != nil && o.BmcIpAddress.IsSet() {
		return true
	}

	return false
}

// SetBmcIpAddress gets a reference to the given NullableString and assigns it to the BmcIpAddress field.
func (o *ExpectedMachine) SetBmcIpAddress(v string) {
	o.BmcIpAddress.Set(&v)
}

// SetBmcIpAddressNil sets the value for BmcIpAddress to be an explicit nil
func (o *ExpectedMachine) SetBmcIpAddressNil() {
	o.BmcIpAddress.Set(nil)
}

// UnsetBmcIpAddress ensures that no value is present for BmcIpAddress, not even an explicit nil
func (o *ExpectedMachine) UnsetBmcIpAddress() {
	o.BmcIpAddress.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ExpectedMachine) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ExpectedMachine) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *ExpectedMachine) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ExpectedMachine) UnsetName() {
	o.Name.Unset()
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer.Get()) {
		var ret string
		return ret
	}
	return *o.Manufacturer.Get()
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Manufacturer.Get(), o.Manufacturer.IsSet()
}

// HasManufacturer returns a boolean if a field has been set.
func (o *ExpectedMachine) HasManufacturer() bool {
	if o != nil && o.Manufacturer.IsSet() {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given NullableString and assigns it to the Manufacturer field.
func (o *ExpectedMachine) SetManufacturer(v string) {
	o.Manufacturer.Set(&v)
}

// SetManufacturerNil sets the value for Manufacturer to be an explicit nil
func (o *ExpectedMachine) SetManufacturerNil() {
	o.Manufacturer.Set(nil)
}

// UnsetManufacturer ensures that no value is present for Manufacturer, not even an explicit nil
func (o *ExpectedMachine) UnsetManufacturer() {
	o.Manufacturer.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *ExpectedMachine) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *ExpectedMachine) SetModel(v string) {
	o.Model.Set(&v)
}

// SetModelNil sets the value for Model to be an explicit nil
func (o *ExpectedMachine) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *ExpectedMachine) UnsetModel() {
	o.Model.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ExpectedMachine) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ExpectedMachine) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ExpectedMachine) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ExpectedMachine) UnsetDescription() {
	o.Description.Unset()
}

// GetSlotId returns the SlotId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetSlotId() int32 {
	if o == nil || IsNil(o.SlotId.Get()) {
		var ret int32
		return ret
	}
	return *o.SlotId.Get()
}

// GetSlotIdOk returns a tuple with the SlotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetSlotIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlotId.Get(), o.SlotId.IsSet()
}

// HasSlotId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasSlotId() bool {
	if o != nil && o.SlotId.IsSet() {
		return true
	}

	return false
}

// SetSlotId gets a reference to the given NullableInt32 and assigns it to the SlotId field.
func (o *ExpectedMachine) SetSlotId(v int32) {
	o.SlotId.Set(&v)
}

// SetSlotIdNil sets the value for SlotId to be an explicit nil
func (o *ExpectedMachine) SetSlotIdNil() {
	o.SlotId.Set(nil)
}

// UnsetSlotId ensures that no value is present for SlotId, not even an explicit nil
func (o *ExpectedMachine) UnsetSlotId() {
	o.SlotId.Unset()
}

// GetTrayIdx returns the TrayIdx field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetTrayIdx() int32 {
	if o == nil || IsNil(o.TrayIdx.Get()) {
		var ret int32
		return ret
	}
	return *o.TrayIdx.Get()
}

// GetTrayIdxOk returns a tuple with the TrayIdx field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetTrayIdxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrayIdx.Get(), o.TrayIdx.IsSet()
}

// HasTrayIdx returns a boolean if a field has been set.
func (o *ExpectedMachine) HasTrayIdx() bool {
	if o != nil && o.TrayIdx.IsSet() {
		return true
	}

	return false
}

// SetTrayIdx gets a reference to the given NullableInt32 and assigns it to the TrayIdx field.
func (o *ExpectedMachine) SetTrayIdx(v int32) {
	o.TrayIdx.Set(&v)
}

// SetTrayIdxNil sets the value for TrayIdx to be an explicit nil
func (o *ExpectedMachine) SetTrayIdxNil() {
	o.TrayIdx.Set(nil)
}

// UnsetTrayIdx ensures that no value is present for TrayIdx, not even an explicit nil
func (o *ExpectedMachine) UnsetTrayIdx() {
	o.TrayIdx.Unset()
}

// GetHostId returns the HostId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetHostId() int32 {
	if o == nil || IsNil(o.HostId.Get()) {
		var ret int32
		return ret
	}
	return *o.HostId.Get()
}

// GetHostIdOk returns a tuple with the HostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetHostIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.HostId.Get(), o.HostId.IsSet()
}

// HasHostId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasHostId() bool {
	if o != nil && o.HostId.IsSet() {
		return true
	}

	return false
}

// SetHostId gets a reference to the given NullableInt32 and assigns it to the HostId field.
func (o *ExpectedMachine) SetHostId(v int32) {
	o.HostId.Set(&v)
}

// SetHostIdNil sets the value for HostId to be an explicit nil
func (o *ExpectedMachine) SetHostIdNil() {
	o.HostId.Set(nil)
}

// UnsetHostId ensures that no value is present for HostId, not even an explicit nil
func (o *ExpectedMachine) UnsetHostId() {
	o.HostId.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedMachine) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedMachine) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedMachine) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ExpectedMachine) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ExpectedMachine) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ExpectedMachine) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ExpectedMachine) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ExpectedMachine) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *ExpectedMachine) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o ExpectedMachine) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedMachine) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.BmcMacAddress) {
		toSerialize["bmcMacAddress"] = o.BmcMacAddress
	}
	if !IsNil(o.ChassisSerialNumber) {
		toSerialize["chassisSerialNumber"] = o.ChassisSerialNumber
	}
	if !IsNil(o.FallbackDPUSerialNumbers) {
		toSerialize["fallbackDPUSerialNumbers"] = o.FallbackDPUSerialNumbers
	}
	if o.SkuId.IsSet() {
		toSerialize["skuId"] = o.SkuId.Get()
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if o.MachineId.IsSet() {
		toSerialize["machineId"] = o.MachineId.Get()
	}
	if !IsNil(o.Machine) {
		toSerialize["machine"] = o.Machine
	}
	if o.RackId.IsSet() {
		toSerialize["rackId"] = o.RackId.Get()
	}
	if o.BmcIpAddress.IsSet() {
		toSerialize["bmcIpAddress"] = o.BmcIpAddress.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Manufacturer.IsSet() {
		toSerialize["manufacturer"] = o.Manufacturer.Get()
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.SlotId.IsSet() {
		toSerialize["slotId"] = o.SlotId.Get()
	}
	if o.TrayIdx.IsSet() {
		toSerialize["trayIdx"] = o.TrayIdx.Get()
	}
	if o.HostId.IsSet() {
		toSerialize["hostId"] = o.HostId.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableExpectedMachine struct {
	value *ExpectedMachine
	isSet bool
}

func (v NullableExpectedMachine) Get() *ExpectedMachine {
	return v.value
}

func (v *NullableExpectedMachine) Set(val *ExpectedMachine) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedMachine) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedMachine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedMachine(val *ExpectedMachine) *NullableExpectedMachine {
	return &NullableExpectedMachine{value: val, isSet: true}
}

func (v NullableExpectedMachine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedMachine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
