// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchUpdateRackPowerStateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchUpdateRackPowerStateRequest{}

// BatchUpdateRackPowerStateRequest Request body for batch rack power control operations
type BatchUpdateRackPowerStateRequest struct {
	// ID of the Site
	SiteId string `json:"siteId"`
	// Filter that selects Racks whose power state should be updated
	Filter *RackFilter `json:"filter,omitempty"`
	// Target power state
	State string `json:"state"`
	// Optional Operation Rule UUID. When set, pins every task spawned by this batch to the named rule and overrides Flow's default rule resolution.
	RuleId *string `json:"ruleId,omitempty"`
	// When true, proceed even if one or more target components (or hosts on the owning rack for rack-scoped components) are reported as not ready by their persisted status. Intended for operator-supervised maintenance.
	OverrideReadinessCheck *bool `json:"overrideReadinessCheck,omitempty"`
}

type _BatchUpdateRackPowerStateRequest BatchUpdateRackPowerStateRequest

// NewBatchUpdateRackPowerStateRequest instantiates a new BatchUpdateRackPowerStateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchUpdateRackPowerStateRequest(siteId string, state string) *BatchUpdateRackPowerStateRequest {
	this := BatchUpdateRackPowerStateRequest{}
	this.SiteId = siteId
	this.State = state
	var overrideReadinessCheck bool = false
	this.OverrideReadinessCheck = &overrideReadinessCheck
	return &this
}

// NewBatchUpdateRackPowerStateRequestWithDefaults instantiates a new BatchUpdateRackPowerStateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchUpdateRackPowerStateRequestWithDefaults() *BatchUpdateRackPowerStateRequest {
	this := BatchUpdateRackPowerStateRequest{}
	var overrideReadinessCheck bool = false
	this.OverrideReadinessCheck = &overrideReadinessCheck
	return &this
}

// GetSiteId returns the SiteId field value
func (o *BatchUpdateRackPowerStateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *BatchUpdateRackPowerStateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *BatchUpdateRackPowerStateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *BatchUpdateRackPowerStateRequest) GetFilter() RackFilter {
	if o == nil || IsNil(o.Filter) {
		var ret RackFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateRackPowerStateRequest) GetFilterOk() (*RackFilter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *BatchUpdateRackPowerStateRequest) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given RackFilter and assigns it to the Filter field.
func (o *BatchUpdateRackPowerStateRequest) SetFilter(v RackFilter) {
	o.Filter = &v
}

// GetState returns the State field value
func (o *BatchUpdateRackPowerStateRequest) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *BatchUpdateRackPowerStateRequest) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *BatchUpdateRackPowerStateRequest) SetState(v string) {
	o.State = v
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *BatchUpdateRackPowerStateRequest) GetRuleId() string {
	if o == nil || IsNil(o.RuleId) {
		var ret string
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateRackPowerStateRequest) GetRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RuleId) {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *BatchUpdateRackPowerStateRequest) HasRuleId() bool {
	if o != nil && !IsNil(o.RuleId) {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given string and assigns it to the RuleId field.
func (o *BatchUpdateRackPowerStateRequest) SetRuleId(v string) {
	o.RuleId = &v
}

// GetOverrideReadinessCheck returns the OverrideReadinessCheck field value if set, zero value otherwise.
func (o *BatchUpdateRackPowerStateRequest) GetOverrideReadinessCheck() bool {
	if o == nil || IsNil(o.OverrideReadinessCheck) {
		var ret bool
		return ret
	}
	return *o.OverrideReadinessCheck
}

// GetOverrideReadinessCheckOk returns a tuple with the OverrideReadinessCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchUpdateRackPowerStateRequest) GetOverrideReadinessCheckOk() (*bool, bool) {
	if o == nil || IsNil(o.OverrideReadinessCheck) {
		return nil, false
	}
	return o.OverrideReadinessCheck, true
}

// HasOverrideReadinessCheck returns a boolean if a field has been set.
func (o *BatchUpdateRackPowerStateRequest) HasOverrideReadinessCheck() bool {
	if o != nil && !IsNil(o.OverrideReadinessCheck) {
		return true
	}

	return false
}

// SetOverrideReadinessCheck gets a reference to the given bool and assigns it to the OverrideReadinessCheck field.
func (o *BatchUpdateRackPowerStateRequest) SetOverrideReadinessCheck(v bool) {
	o.OverrideReadinessCheck = &v
}

func (o BatchUpdateRackPowerStateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchUpdateRackPowerStateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	toSerialize["state"] = o.State
	if !IsNil(o.RuleId) {
		toSerialize["ruleId"] = o.RuleId
	}
	if !IsNil(o.OverrideReadinessCheck) {
		toSerialize["overrideReadinessCheck"] = o.OverrideReadinessCheck
	}
	return toSerialize, nil
}

func (o *BatchUpdateRackPowerStateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchUpdateRackPowerStateRequest := _BatchUpdateRackPowerStateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchUpdateRackPowerStateRequest)

	if err != nil {
		return err
	}

	*o = BatchUpdateRackPowerStateRequest(varBatchUpdateRackPowerStateRequest)

	return err
}

type NullableBatchUpdateRackPowerStateRequest struct {
	value *BatchUpdateRackPowerStateRequest
	isSet bool
}

func (v NullableBatchUpdateRackPowerStateRequest) Get() *BatchUpdateRackPowerStateRequest {
	return v.value
}

func (v *NullableBatchUpdateRackPowerStateRequest) Set(val *BatchUpdateRackPowerStateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchUpdateRackPowerStateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchUpdateRackPowerStateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchUpdateRackPowerStateRequest(val *BatchUpdateRackPowerStateRequest) *NullableBatchUpdateRackPowerStateRequest {
	return &NullableBatchUpdateRackPowerStateRequest{value: val, isSet: true}
}

func (v NullableBatchUpdateRackPowerStateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchUpdateRackPowerStateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
